#:include 'generics.fypp'
!----------------------------------------------------------------------
! Module: type_geom
!> Geometry derived type
! Author: Benjamin Menetrier
! Licensing: this code is distributed under the CeCILL-C license
! Copyright 2015-... UCAR, CERFACS, METEO-FRANCE and IRIT
!----------------------------------------------------------------------
module type_geom

use atlas_module, only: atlas_config,atlas_field,atlas_functionspace, &
 & atlas_functionspace_nodecolumns,atlas_functionspace_pointcloud,atlas_functionspace_structuredcolumns, &
 & atlas_mesh_nodes,atlas_projection,atlas_structuredgrid
use fckit_mpi_module, only: fckit_mpi_sum,fckit_mpi_min,fckit_mpi_max
!$ use omp_lib
use tools_atlas, only: get_grid,field_to_array,get_atlas_functionspace_size
use tools_const, only: zero,half,one,two,three,four,hundred,pi,deg2rad,rad2deg,reqkm
use tools_fit, only: work_grid
use tools_func, only: lonlatmod,grid_hash,independent_levels,sphere_dist,lonlat2xyz,xyz2lonlat,cart_dist, &
 & vector_product,area,cx_to_cxa,cx_to_proc,cx_to_cxu,convert_l2i,convert_i2l,zss_minval,zss_maxval,zss_sum,zss_count
use tools_kinds, only: kind_int,kind_real,huge_real
use tools_qsort, only: qsort
use tools_repro, only: inf,sup,eq,supeq,indist,repro_th
use type_bnda, only: bnda_type
use type_com, only: com_type
use type_fieldset, only: fieldset_type
use type_hull, only: hull_type
use type_io, only: io_type
use type_mesh, only: mesh_type
use type_minim, only: minim_type
use type_mpl, only: mpl_type
use type_nam, only: nam_type
use type_rng, only: rng_type
use type_tree, only: tree_type

implicit none

! Geometry derived type
type geom_type
   ! Deprecation flags
   logical :: deprecated_hull                         !< Use deprecated hull
   logical :: deprecated_work_grid                    !< Use deprecated work grid

   ! Number of tasks
   integer :: nproc                                   !< Number of tasks

   ! Input metadata
   logical,allocatable :: owned_mga(:,:)              !< Owned vs Halo/BC

   ! Domain type
   logical :: global                                  !< Global grid flag (regional if false)

   ! Regional work grid
   type(atlas_config) :: aconfig_work_grid            !< Work grid configuration
   type(atlas_projection) :: aproj_work               !< Work grid projection
   real(kind_real) :: v_center(3)                     !< Work grid center in cartesian coordinates
   real(kind_real) :: xmin                            !< Computational work grid minimum x value
   real(kind_real) :: xmax                            !< Computational work grid maximum x value
   real(kind_real) :: ymin                            !< Computational work grid minimum y value
   real(kind_real) :: ymax                            !< Computational work grid maximum y value

   ! Geometry data on model grid, halo A
   integer :: nmga                                    !< Halo A size for model grid
   real(kind_real),allocatable :: lon_mga(:)          !< Longitudes
   real(kind_real),allocatable :: lat_mga(:)          !< Latitudes
   real(kind_real),allocatable :: vert_coord_mga(:,:) !< Generalized vertical coordinate
   logical,allocatable :: gmask_mga(:,:)              !< Geometry mask
   type(atlas_functionspace) :: afunctionspace_mg     !< ATLAS function space of model grid

   ! Link between model grid and subset Sc0 on halo A
   integer,allocatable :: c0a_to_mga(:)               !< Subset Sc0 to model grid on halo A

   ! Geometry data on model grid, full domain
   integer :: nmg                                     !< Number of model grid points

   ! Universe
   logical,allocatable :: myuniverse(:)               !< MPI tasks in the universe of the local task
   real(kind_real) :: universe_proportion             !< Proportion of the total domain handled in the universe

   ! Geometry data on subset Sc0, halo A
   integer,allocatable :: proc_to_nc0a(:)             !< Task to halo A size for subset Sc0
   integer :: nc0a                                    !< Halo A size for subset Sc0
   logical :: same_grid                               !< Same grid and distribution flag
   real(kind_real),allocatable :: lon_c0a(:)          !< Longitudes
   real(kind_real),allocatable :: lat_c0a(:)          !< Latitudes
   real(kind_real),allocatable :: vert_coord_c0a(:,:) !< Generalized vertical coordinate
   logical,allocatable :: gmask_c0a(:,:)              !< Geometry mask
   logical,allocatable :: gmask_hor_c0a(:)            !< Union of horizontal geometry masks
   real(kind_real),allocatable :: mdist_c0a(:,:)      !< Minimum distance to mask

   ! Geometry data on subset Sc0, universe
   integer,allocatable :: proc_to_nc0u(:)             !< Task to universe size for subset Sc0
   integer :: nc0u                                    !< Universe size for subset Sc0
   real(kind_real),allocatable :: lon_c0u(:)          !< Longitudes
   real(kind_real),allocatable :: lat_c0u(:)          !< Latitudes
   real(kind_real),allocatable :: vert_coord_c0u(:,:) !< Generalized vertical coordinate
   logical,allocatable :: gmask_c0u(:,:)              !< Geometry mask
   logical,allocatable :: gmask_hor_c0u(:)            !< Union of horizontal geometry masks
   real(kind_real),allocatable :: mdist_c0u(:,:)      !< Minimum distance to mask

   ! Geometry data on subset Sc0, full domain
   integer :: nc0                                     !< Number of subset Sc0 points
   integer,allocatable :: proc_to_c0_offset(:)        !< Task to offset on subset Sc0
   integer,allocatable :: nc0_gmask(:)                !< Horizontal mask size on subset Sc0
   real(kind_real) :: area                            !< Domain area
   real(kind_real),allocatable :: area_ver_c0(:)      !< Area profile on subset Sc0
   real(kind_real) :: area_max_c0                     !< Area maximum on subset Sc0

   ! Link between halo A and universe on subset Sc0
   integer,allocatable :: c0a_to_c0u(:)               !< Halo A to universe on subset Sc0
   integer,allocatable :: c0u_to_c0a(:)               !< Universe to halo A on subset Sc0
   type(com_type) :: com_AU                           !< Communication between halo A and universe on subset Sc0

   ! Link between halo A and full domain on subset Sc0
   integer,allocatable :: c0a_to_c0(:)                !< Subset Sc0, halo A to full domain

   ! Link between universe and full domain on subset Sc0
   integer,allocatable :: c0u_to_c0(:)                !< Subset Sc0, universe to full domain

   ! Number of levels
   integer :: nl0                                     !< Number of levels in subset Sl0
   integer,allocatable :: l0rl0_to_l0(:,:)            !< Reduced level to level
   integer,allocatable :: il0rz(:)                    !< Reduced level at zero separation
   integer :: nl0i                                    !< Number of independent levels in subset Sl0
   integer,allocatable :: l0_to_l0i(:)                !< Levels to independent levels in Sl0
   integer,allocatable :: l0i_to_l0(:)                !< Independent levels to level in Sl0

   ! 2D groups
   logical,allocatable :: grp2d(:)                    !< 2D groups (for which all variables are 2D)
   integer :: nl2d                                    !< 2D level index

   ! Other fields
   real(kind_real),allocatable :: vert_coordavg(:)    !< Averaged vertical coordinate
   real(kind_real),allocatable :: disth(:)            !< Horizontal distance
   real(kind_real),allocatable :: as(:)               !< Angular sectors
   real(kind_real) :: das                             !< Angular sector width

   ! Tree
   type(tree_type) :: tree_c0u                        !< Tree on subset Sc0, universe
   type(tree_type) :: tree_c0                         !< Tree on subset Sc0, full domain

   ! Mesh
   type(mesh_type) :: mesh_c0u                        !< Mesh on subset Sc0, universe

   ! Mask boundaries
   type(bnda_type) :: bnda_c0u                        !< Mask boundaries on subset Sc0, universe

   ! Hull
   type(hull_type) :: hull_c0u                        !< Domain hull on subset Sc0, universe
   type(hull_type) :: hull_c0                         !< Domain hull on subset Sc0, full domain

   ! Dirac fields for variables
   integer :: ndir                                    !< Number of valid Dirac points
   real(kind_real),allocatable :: londir(:)           !< Dirac longitude
   real(kind_real),allocatable :: latdir(:)           !< Dirac latitude
   integer,allocatable :: iprocdir(:)                 !< Dirac task
   integer,allocatable :: ic0adir(:)                  !< Dirac gridpoint
   integer,allocatable :: il0dir(:)                   !< Dirac level
   integer,allocatable :: ivdir(:)                    !< Dirac field index
   integer,allocatable :: inbdir(:,:)                 !< Neighboring dirac index

   ! I/O
   type(io_type) :: io                                !< Subset Sc0 I/O
   integer,allocatable :: order_c0(:)                 !< Subset Sc0 points order for global I/O

   ! Allocation flag
   logical :: allocated                               !< Allocation flag
contains
   procedure :: partial_dealloc => geom_partial_dealloc
   procedure :: dealloc => geom_dealloc
   procedure :: setup => geom_setup
   procedure :: from_atlas => geom_from_atlas
   procedure :: setup_c0 => geom_setup_c0
   procedure :: setup_universe => geom_setup_universe
   procedure :: setup_hulls => geom_setup_hulls
   procedure :: setup_grid => geom_setup_grid
   procedure :: lonlat_to_c0 => geom_lonlat_to_c0
   procedure :: setup_dirac => geom_setup_dirac
   #:for dtype in dtypes_irl
      procedure :: geom_copy_c0a_to_mga_${dtype}$_single
      procedure :: geom_copy_c0a_to_mga_${dtype}$_all
      procedure :: geom_copy_mga_to_c0a_${dtype}$_single
      procedure :: geom_copy_mga_to_c0a_${dtype}$_all
   #:endfor
@:init_procedure(6)
   generic :: copy_c0a_to_mga => &
   #:for dtype in dtypes_irl
@:add_procedure(geom_copy_c0a_to_mga_${dtype}$_single)
@:add_procedure(geom_copy_c0a_to_mga_${dtype}$_all)
   #:endfor
@:init_procedure(6)
   generic :: copy_mga_to_c0a => &
   #:for dtype in dtypes_irl
@:add_procedure(geom_copy_mga_to_c0a_${dtype}$_single)
@:add_procedure(geom_copy_mga_to_c0a_${dtype}$_all)
   #:endfor
   procedure :: fieldset_to_c0 => geom_fieldset_to_c0
   procedure :: c0_to_fieldset => geom_c0_to_fieldset
   procedure :: rand_points => geom_rand_points
   procedure :: geom_initialize_sampling_from_size
   procedure :: geom_initialize_sampling_from_rad
   generic :: initialize_sampling => geom_initialize_sampling_from_size,geom_initialize_sampling_from_rad
   procedure :: define_test_vectors => geom_define_test_vectors
   procedure :: c0_to_c0a => geom_c0_to_c0a
   procedure :: c0_to_proc => geom_c0_to_proc
   procedure :: c0_to_c0u => geom_c0_to_c0u
end type geom_type


integer,parameter :: niter = 10                  !< Number of iterations to estimate the work grid inflation
integer,parameter :: na_bridson = 6              !< Number of angles for the Bridson's method
integer,parameter :: nd_bridson = 5              !< Number of distances for the Bridson's method
real(kind_real),parameter :: grid_factor = three !< Grid factor for the Bridson's method

private
public :: geom_type

contains

!----------------------------------------------------------------------
! Subroutine: geom_partial_dealloc
!> Release memory (partial)
!----------------------------------------------------------------------
subroutine geom_partial_dealloc(geom)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom !< Geometry

! Set name
@:set_name(geom_partial_dealloc)

! Release memory
if (allocated(geom%l0rl0_to_l0)) deallocate(geom%l0rl0_to_l0)
if (allocated(geom%il0rz)) deallocate(geom%il0rz)
if (allocated(geom%lon_mga)) deallocate(geom%lon_mga)
if (allocated(geom%lat_mga)) deallocate(geom%lat_mga)
if (allocated(geom%vert_coord_mga)) deallocate(geom%vert_coord_mga)
if (allocated(geom%myuniverse)) deallocate(geom%myuniverse)
if (allocated(geom%proc_to_nc0a)) deallocate(geom%proc_to_nc0a)
if (allocated(geom%gmask_hor_c0a)) deallocate(geom%gmask_hor_c0a)
if (allocated(geom%mdist_c0a)) deallocate(geom%mdist_c0a)
if (allocated(geom%proc_to_nc0u)) deallocate(geom%proc_to_nc0u)
if (allocated(geom%lon_c0u)) deallocate(geom%lon_c0u)
if (allocated(geom%lat_c0u)) deallocate(geom%lat_c0u)
if (allocated(geom%vert_coord_c0u)) deallocate(geom%vert_coord_c0u)
if (allocated(geom%gmask_c0u)) deallocate(geom%gmask_c0u)
if (allocated(geom%gmask_hor_c0u)) deallocate(geom%gmask_hor_c0u)
if (allocated(geom%mdist_c0u)) deallocate(geom%mdist_c0u)
if (allocated(geom%proc_to_c0_offset)) deallocate(geom%proc_to_c0_offset)
if (allocated(geom%c0a_to_c0u)) deallocate(geom%c0a_to_c0u)
if (allocated(geom%c0u_to_c0a)) deallocate(geom%c0u_to_c0a)
call geom%com_AU%dealloc
if (allocated(geom%c0a_to_c0)) deallocate(geom%c0a_to_c0)
if (allocated(geom%c0u_to_c0)) deallocate(geom%c0u_to_c0)
if (allocated(geom%nc0_gmask)) deallocate(geom%nc0_gmask)
if (allocated(geom%l0i_to_l0)) deallocate(geom%l0i_to_l0)
if (allocated(geom%area_ver_c0)) deallocate(geom%area_ver_c0)
if (allocated(geom%vert_coordavg)) deallocate(geom%vert_coordavg)
if (allocated(geom%disth)) deallocate(geom%disth)
if (allocated(geom%as)) deallocate(geom%as)
call geom%tree_c0u%dealloc
call geom%tree_c0%dealloc
call geom%mesh_c0u%dealloc
call geom%bnda_c0u%dealloc
if (allocated(geom%londir)) deallocate(geom%londir)
if (allocated(geom%latdir)) deallocate(geom%latdir)
if (allocated(geom%iprocdir)) deallocate(geom%iprocdir)
if (allocated(geom%ic0adir)) deallocate(geom%ic0adir)
if (allocated(geom%il0dir)) deallocate(geom%il0dir)
if (allocated(geom%ivdir)) deallocate(geom%ivdir)
if (allocated(geom%inbdir)) deallocate(geom%inbdir)
if (allocated(geom%order_c0)) deallocate(geom%order_c0)

end subroutine geom_partial_dealloc

!----------------------------------------------------------------------
! Subroutine: geom_dealloc
!> Release memory
!----------------------------------------------------------------------
subroutine geom_dealloc(geom)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom !< Geometry

! Set name
@:set_name(geom_dealloc)

! Release memory
call geom%partial_dealloc
call geom%afunctionspace_mg%final()
if (allocated(geom%gmask_mga)) deallocate(geom%gmask_mga)
if (allocated(geom%c0a_to_mga)) deallocate(geom%c0a_to_mga)
if (allocated(geom%lon_c0a)) deallocate(geom%lon_c0a)
if (allocated(geom%lat_c0a)) deallocate(geom%lat_c0a)
if (allocated(geom%vert_coord_c0a)) deallocate(geom%vert_coord_c0a)
if (allocated(geom%gmask_c0a)) deallocate(geom%gmask_c0a)
call geom%hull_c0u%dealloc
call geom%hull_c0%dealloc
if (allocated(geom%l0_to_l0i)) deallocate(geom%l0_to_l0i)
if (allocated(geom%grp2d)) deallocate(geom%grp2d)
call geom%io%dealloc
call geom%aconfig_work_grid%final()
call geom%aproj_work%final()
call geom%afunctionspace_mg%final()
geom%allocated = .false.

end subroutine geom_dealloc

!----------------------------------------------------------------------
! Subroutine: geom_setup
!> Setup geometry
!----------------------------------------------------------------------
subroutine geom_setup(geom,mpl,rng,nam,afunctionspace,fieldset)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom                 !< Geometry
type(mpl_type),intent(inout) :: mpl                    !< MPI data
type(rng_type),intent(inout) :: rng                    !< Random number generator
type(nam_type),intent(in) :: nam                       !< Namelist
type(atlas_functionspace),intent(in) :: afunctionspace !< ATLAS function space
type(fieldset_type),intent(in),optional :: fieldset    !< Fieldset containing geometry elements

! Local variables
integer :: il0,jl0off,jl0r,jc3,jc4,iproc,iv,ig
integer,allocatable :: order_c0a(:)
real(kind_real),allocatable :: lon_c0(:),lat_c0(:)

! Set name
@:set_name(geom_setup)

! Deprecation flags
geom%deprecated_hull = nam%deprecated_hull
geom%deprecated_work_grid = nam%deprecated_work_grid

! Number of task
geom%nproc = mpl%nproc

! Number of levels
geom%nl0 = nam%nl0

! Reduced number of levels
allocate(geom%l0rl0_to_l0(nam%nl0r,geom%nl0))
allocate(geom%il0rz(geom%nl0))
do il0=1,geom%nl0
   jl0off = il0-(nam%nl0r-1)/2-1
   if (jl0off<1) jl0off = 0
   if (jl0off+nam%nl0r>geom%nl0) jl0off = geom%nl0-nam%nl0r
   do jl0r=1,nam%nl0r
      geom%l0rl0_to_l0(jl0r,il0) = jl0off+jl0r
      if (geom%l0rl0_to_l0(jl0r,il0)==il0) geom%il0rz(il0) = jl0r
   end do
end do

! Get 2D groups
allocate(geom%grp2d(nam%ng))
geom%grp2d = .true.
do iv=1,nam%nv
  ig = nam%group_index(iv)
  if (.not.nam%var2d(iv)) geom%grp2d(ig) = .false.
end do
if (trim(nam%lev2d)=='first') then
   geom%nl2d = 1
else if (trim(nam%lev2d)=='last') then
   geom%nl2d = geom%nl0
end if

! Copy function space pointer
if (present(fieldset)) then
   call geom%from_atlas(mpl,nam,afunctionspace,fieldset)
else
   call geom%from_atlas(mpl,nam,afunctionspace)
end if

! Setup subset Sc0
call geom%setup_c0(mpl)

! Allocation
if (mpl%main) then
   allocate(lon_c0(geom%nc0))
   allocate(lat_c0(geom%nc0))
else
   allocate(lon_c0(0))
   allocate(lat_c0(0))
end if

! Communication
call mpl%loc_to_glb(geom%nc0a,geom%nc0,geom%c0a_to_c0,geom%lon_c0a,lon_c0)
call mpl%loc_to_glb(geom%nc0a,geom%nc0,geom%c0a_to_c0,geom%lat_c0a,lat_c0)

! Setup universe
call geom%setup_universe(mpl,nam)

! Setup tree
write(mpl%info,'(a7,a)') '','Setup tree'
call mpl%flush
call geom%tree_c0u%init(mpl,geom%nc0u,geom%lon_c0u,geom%lat_c0u)
if (mpl%main) call geom%tree_c0%init(mpl,geom%nc0,lon_c0,lat_c0)

if (nam%mask_check.or.(.not.geom%global)) then
   if (geom%deprecated_hull) then
      ! Reseed for backward compatibility
      call rng%reseed
   end if

   ! Setup mesh
   write(mpl%info,'(a7,a)') '','Setup mesh'
   call mpl%flush
   call geom%mesh_c0u%init(mpl,rng,geom%nc0u,geom%lon_c0u,geom%lat_c0u)
else
   ! Set number of boundary nodes to zero
   geom%mesh_c0u%nb = 0
end if

! Setup hulls
write(mpl%info,'(a7,a)') '','Setup hulls'
call mpl%flush
call geom%setup_hulls(mpl,rng,nam)

! Setup grid properties
write(mpl%info,'(a7,a)') '','Setup grid properties'
call mpl%flush
call geom%setup_grid(mpl,rng)

if (nam%mask_check) then
   ! Setup mask boundaries
   write(mpl%info,'(a7,a)') '','Setup mask boundaries'
   call mpl%flush
   call geom%bnda_c0u%init(mpl,geom%nc0u,geom%nl0,geom%gmask_hor_c0u,geom%gmask_c0u,geom%mesh_c0u)
end if

! Setup horizontal distance
write(mpl%info,'(a7,a)') '','Setup horizontal distance'
call mpl%flush
allocate(geom%disth(nam%nc3))
do jc3=1,nam%nc3
   geom%disth(jc3) = real(jc3-1,kind_real)*nam%dc
end do
if (maxval(geom%disth)>nam%universe_radius) call mpl%abort('${subr}$','horizontal distance larger than universe radius')

! Setup angular sector
write(mpl%info,'(a7,a)') '','Setup angular sector'
call mpl%flush
allocate(geom%as(nam%nc4))
geom%das = pi/real(nam%nc4,kind_real)
do jc4=1,nam%nc4
   geom%as(jc4) = -pi*half+real(jc4-1,kind_real)*geom%das
end do

! Setup dirac points
call geom%setup_dirac(mpl,nam)

! Set allocation flag
geom%allocated = .true.

if ((nam%write_nicas_global.or.nam%load_nicas_global).or.(nam%write_wind_global.or.nam%load_wind_global)) then
   if (mpl%main.or.(nam%write_wind_global.or.nam%load_wind_global)) then
      allocate(geom%order_c0(geom%nc0))
   else
      allocate(geom%order_c0(0))
   end if
   allocate(order_c0a(geom%nc0a))

   ! Compute global order
   if (mpl%main) call qsort(geom%nc0,lon_c0,lat_c0,geom%order_c0,.false.)
   call mpl%glb_to_loc(geom%nc0a,geom%nc0,geom%c0a_to_c0,geom%order_c0,order_c0a)

   ! Broadcast global order
   if (nam%write_wind_global.or.nam%load_wind_global) call mpl%f_comm%broadcast(geom%order_c0,mpl%rootproc-1)

   ! Setup fields output
   call geom%io%init(mpl,7,'0',geom%nc0,geom%nc0a,geom%c0a_to_c0,geom%proc_to_c0_offset,order_c0a)

   ! Release memory
   if (.not.(nam%write_wind_global.or.nam%load_wind_global)) deallocate(geom%order_c0)
   deallocate(order_c0a)
end if

! Release memory
deallocate(lon_c0)
deallocate(lat_c0)

! Print summary
write(mpl%info,'(a7,a)') '','Geometry summary:'
call mpl%flush
write(mpl%info,'(a10,a,i8)') '','Model grid size:         ',geom%nmg
call mpl%flush
write(mpl%test,'(a10,a,i8)') '','Subset Sc0 size:         ',geom%nc0
call mpl%flush
write(mpl%info,'(a10,a,i6,a,f6.2,a)') '','Number of duplicated points (halo):    ',(geom%nmg-geom%nc0), &
 & ' (',real(geom%nmg-geom%nc0,kind_real)/real(geom%nmg,kind_real)*hundred,'%)'
call mpl%flush
write(mpl%test,'(a10,a,e10.3,a)') '','Domain area (% of Earth area):',hundred*geom%area_max_c0/(four*pi),'%'
call mpl%flush
write(mpl%info,'(a10,a)') '','Valid points (% of total domain):'
call mpl%flush
do il0=1,geom%nl0
   write(mpl%test,'(a13,a,i3,a,f5.1,a)') '','Level ',il0,' ~> ', &
 & hundred*real(geom%nc0_gmask(il0),kind_real)/real(geom%nc0,kind_real),'%'
   call mpl%flush
end do
write(mpl%info,'(a10,a)') '','Vertical coordinate:'
call mpl%flush
do il0=1,geom%nl0
   write(mpl%test,'(a13,a,i3,a,e10.3,a)') '','Level ',il0,' ~> ',geom%vert_coordavg(il0),' vert. coord.'
   call mpl%flush
end do
write(mpl%info,'(a10,a)') '','Distribution (local / universe):'
call mpl%flush
do iproc=1,mpl%nproc
   write(mpl%info,'(a13,a,i6,a,i8,a,i8)') '','Task ',iproc,': ',geom%proc_to_nc0a(iproc),' / ',geom%proc_to_nc0u(iproc)
   call mpl%flush
end do

end subroutine geom_setup

!----------------------------------------------------------------------
! Subroutine: geom_from_atlas
!> Set geometry from fieldset
!----------------------------------------------------------------------
subroutine geom_from_atlas(geom,mpl,nam,afunctionspace,fieldset)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom                 !< Geometry
type(mpl_type),intent(inout) :: mpl                    !< MPI data
type(nam_type),intent(in) :: nam                       !< Namelist
type(atlas_functionspace),intent(in) :: afunctionspace !< ATLAS function space
type(fieldset_type),intent(in),optional :: fieldset    !< Fieldset

! Local variables
integer :: il0,imga
real(kind_real) :: lon0,lat0,dist,maxdist
real(kind_real),pointer :: real_ptr(:,:)
type(atlas_field) :: afield,afield_lonlat
type(atlas_functionspace_nodecolumns) :: afunctionspace_nc
type(atlas_functionspace_pointcloud) :: afunctionspace_pc
type(atlas_functionspace_structuredcolumns) :: afunctionspace_sc
type(atlas_mesh_nodes) :: anodes

! Set name
@:set_name(geom_from_atlas)

! Copy function space
geom%afunctionspace_mg = atlas_functionspace(afunctionspace%c_ptr())

! Get number of points
geom%nmga = get_atlas_functionspace_size(mpl,geom%afunctionspace_mg)

! Total number of points
call mpl%f_comm%allreduce(geom%nmga,geom%nmg,fckit_mpi_sum())

! Allocation
allocate(geom%owned_mga(geom%nmga,1))
allocate(geom%vert_coord_mga(geom%nmga,geom%nl0))
allocate(geom%gmask_mga(geom%nmga,geom%nl0))
allocate(geom%lon_mga(geom%nmga))
allocate(geom%lat_mga(geom%nmga))

! Default values
geom%owned_mga = .true.
do il0=1,geom%nl0
   geom%vert_coord_mga(:,il0) = real(il0,kind_real)
end do
geom%gmask_mga = .true.

if (present(fieldset)) then
   ! Get owned vs halo/BC field
   if (fieldset%has_field('owned')) then
      afield = fieldset%field('owned')
      call field_to_array(afield,mpl,geom%owned_mga)
      call afield%final()
   end if

   ! Get vertical coordinate
   if (nam%vert_coord_name /= '') then
      afield = fieldset%field(nam%vert_coord_name)
      call field_to_array(afield,mpl,geom%vert_coord_mga)
      call afield%final()
   end if

   ! Get geometry mask
   if (nam%gmask_name /= '') then
      afield = fieldset%field(nam%gmask_name)
      call field_to_array(afield,mpl,geom%gmask_mga)
      call afield%final()
   end if
end if

! Get lon/lat
select case (afunctionspace%name())
case ('NodeColumns')
   ! Get node columns function space
   afunctionspace_nc = afunctionspace

   ! Get lon/lat field
   anodes = afunctionspace_nc%nodes()
   afield_lonlat = anodes%lonlat()
   call afield_lonlat%data(real_ptr)
   if (geom%nmga>0) then
      geom%lon_mga = real_ptr(1,:)*deg2rad
      geom%lat_mga = real_ptr(2,:)*deg2rad
   end if
case ('PointCloud')
   ! Get point cloud function space
   afunctionspace_pc = afunctionspace

   ! Get lon/lat field
   afield_lonlat = afunctionspace_pc%lonlat()
   call afield_lonlat%data(real_ptr)
   if (geom%nmga>0) then
     geom%lon_mga = real_ptr(1,:)*deg2rad
     geom%lat_mga = real_ptr(2,:)*deg2rad
   end if
case ('StructuredColumns')
   ! Get structured columns function space
   afunctionspace_sc = afunctionspace

   ! Get lon/lat
   afield_lonlat = afunctionspace_sc%xy()
   call afield_lonlat%data(real_ptr)
   if (geom%nmga>0) then
     geom%lon_mga = real_ptr(1,:)*deg2rad
     geom%lat_mga = real_ptr(2,:)*deg2rad
   end if
case default
   call mpl%abort('${subr}$','wrong function space: '//afunctionspace%name())
end select

! Enforce proper bounds
do imga=1,geom%nmga
   if (geom%owned_mga(imga,1)) call lonlatmod(geom%lon_mga(imga),geom%lat_mga(imga))
end do

! Setup global flag
if (mpl%main) then
   lon0 = geom%lon_mga(1)
   lat0 = geom%lat_mga(1)
end if
call mpl%f_comm%broadcast(lon0,mpl%rootproc-1)
call mpl%f_comm%broadcast(lat0,mpl%rootproc-1)
maxdist = zero
do imga=1,geom%nmga
   if (geom%owned_mga(imga,1)) then
       call sphere_dist(lon0,lat0,geom%lon_mga(imga),geom%lat_mga(imga),dist)
       if (dist>maxdist) maxdist = dist
   end if
end do
call mpl%f_comm%allreduce(maxdist,fckit_mpi_max())
geom%global = supeq(maxdist,pi)

! Release memory
call afield%final()
call afield_lonlat%final()
call afunctionspace_nc%final()
call afunctionspace_pc%final()
call afunctionspace_sc%final()
call anodes%final()

end subroutine geom_from_atlas

!----------------------------------------------------------------------
! Subroutine: geom_setup_c0
!> Setup subset Sc0
!----------------------------------------------------------------------
subroutine geom_setup_c0(geom,mpl)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom !< Geometry
type(mpl_type),intent(inout) :: mpl    !< MPI data

! Local variables
integer :: iproc,imga,ic0a,ic0,diff_grid,il0

! Set name
@:set_name(geom_setup_c0)

write(mpl%info,'(a7,a)') '','Setup subset Sc0'
call mpl%flush

! Allocation
allocate(geom%proc_to_nc0a(mpl%nproc))

if (all(geom%owned_mga)) then
   ! No duplicated points (no halo)
   geom%nc0a = geom%nmga
else
   ! Duplicated points present (halo)
   geom%nc0a = count(geom%owned_mga)
end if

! Check grid similarity
if (geom%nc0a==geom%nmga) then
   diff_grid = 0
else
   diff_grid = 1
end if
call mpl%f_comm%allreduce(diff_grid,fckit_mpi_sum())
geom%same_grid = (diff_grid==0)

! Communication
call mpl%f_comm%allgather(geom%nc0a,geom%proc_to_nc0a)

! Subset Sc0 full domain size
geom%nc0 = sum(geom%proc_to_nc0a)

! Allocation
allocate(geom%proc_to_c0_offset(mpl%nproc))
allocate(geom%c0a_to_c0(geom%nc0a))
allocate(geom%c0a_to_mga(geom%nc0a))
allocate(geom%lon_c0a(geom%nc0a))
allocate(geom%lat_c0a(geom%nc0a))
allocate(geom%vert_coord_c0a(geom%nc0a,geom%nl0))
allocate(geom%gmask_c0a(geom%nc0a,geom%nl0))
allocate(geom%gmask_hor_c0a(geom%nc0a))
allocate(geom%nc0_gmask(0:geom%nl0))
allocate(geom%area_ver_c0(geom%nl0))
allocate(geom%vert_coordavg(geom%nl0))
allocate(geom%l0_to_l0i(geom%nl0))
allocate(geom%l0i_to_l0(geom%nl0))

! Subset Sc0 offset for halo A
geom%proc_to_c0_offset(1) = 0
do iproc=2,mpl%nproc
   geom%proc_to_c0_offset(iproc) = geom%proc_to_c0_offset(iproc-1)+geom%proc_to_nc0a(iproc-1)
end do

! Conversion
do ic0a=1,geom%nc0a
   ic0 = geom%proc_to_c0_offset(mpl%myproc)+ic0a
   geom%c0a_to_c0(ic0a) = ic0
end do
ic0a = 0
do imga=1,geom%nmga
   if (geom%owned_mga(imga,1)) then
      ic0a = ic0a+1
      geom%c0a_to_mga(ic0a) = imga
   end if
end do

if (geom%same_grid) then
   ! Copy fields
   geom%lon_c0a = geom%lon_mga
   geom%lat_c0a = geom%lat_mga
   geom%vert_coord_c0a = geom%vert_coord_mga
   geom%gmask_c0a = geom%gmask_mga
else
   ! Copy fields from model grid to subset Sc0 on halo A
   do ic0a=1,geom%nc0a
      imga = geom%c0a_to_mga(ic0a)
      geom%lon_c0a(ic0a) = geom%lon_mga(imga)
      geom%lat_c0a(ic0a) = geom%lat_mga(imga)
      geom%vert_coord_c0a(ic0a,:) = geom%vert_coord_mga(imga,:)
      geom%gmask_c0a(ic0a,:) = geom%gmask_mga(imga,:)
   end do
end if

! Horizontally averaged mask
if (geom%nc0a>0) geom%gmask_hor_c0a = any(geom%gmask_c0a,dim=2)
geom%nc0_gmask(0) = zss_count(geom%gmask_hor_c0a)
do il0=1,geom%nl0
   geom%nc0_gmask(il0) = zss_count(geom%gmask_c0a(:,il0))
end do
call mpl%f_comm%allreduce(geom%nc0_gmask,fckit_mpi_sum())

! Release memory
if (.not.geom%deprecated_hull) then
   deallocate(geom%lon_mga)
   deallocate(geom%lat_mga)
   deallocate(geom%vert_coord_mga)
end if

end subroutine geom_setup_c0

!----------------------------------------------------------------------
! Subroutine: geom_setup_universe
!> Setup universe
!----------------------------------------------------------------------
subroutine geom_setup_universe(geom,mpl,nam)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom !< Geometry
type(mpl_type),intent(inout) :: mpl    !< MPI data
type(nam_type),intent(in) :: nam       !< Namelist

! Local variables
integer :: iproc,ic0a,ic0u,ic0
integer :: proc_to_universe_size(mpl%nproc),proc_to_universe_proportion(mpl%nproc)
integer,allocatable :: order(:)
real(kind_real) :: dist,lon_avg,lat_avg,dist_max
real(kind_real) :: xyz(3),xyz_avg(3)
real(kind_real),allocatable :: proc_to_lon(:),proc_to_lat(:),proc_to_dist_max(:)

! Set name
@:set_name(geom_setup_universe)

write(mpl%info,'(a7,a)') '','Setup universe'
call mpl%flush

! Allocation
allocate(geom%myuniverse(mpl%nproc))

if (mpl%nproc==1) then
   ! Single-task case
   geom%myuniverse = .true.
else
   ! Allocation
   allocate(proc_to_lon(mpl%nproc))
   allocate(proc_to_lat(mpl%nproc))
   allocate(proc_to_dist_max(mpl%nproc))

   ! Initialization
   xyz_avg = zero
   dist_max = zero

   ! Convert to cartesian coordinates and average
   do ic0a=1,geom%nc0a
      call lonlat2xyz(mpl,geom%lon_c0a(ic0a),geom%lat_c0a(ic0a),xyz(1),xyz(2),xyz(3))
      xyz_avg = xyz_avg+xyz
   end do
   if (any(abs(xyz_avg)>zero)) then
      ! Convert average back to lon/lat
      call xyz2lonlat(mpl,xyz_avg(1),xyz_avg(2),xyz_avg(3),lon_avg,lat_avg)

      ! Compute maximum distance to average
      do ic0a=1,geom%nc0a
         if (any(geom%gmask_c0a(ic0a,:))) then
            call sphere_dist(lon_avg,lat_avg,geom%lon_c0a(ic0a),geom%lat_c0a(ic0a),dist)
            if (sup(dist,dist_max)) dist_max = dist
         end if
      end do
   else
      ! Missing values
      lon_avg = mpl%msv%valr
      lat_avg = mpl%msv%valr
   end if

   ! Communication
   call mpl%f_comm%allgather(lon_avg,proc_to_lon)
   call mpl%f_comm%allgather(lat_avg,proc_to_lat)
   call mpl%f_comm%allgather(dist_max,proc_to_dist_max)

   ! Compute distances from sampling points to my task to other sampling points
   geom%myuniverse = .false.
   do iproc=1,geom%nproc
      if (mpl%msv%isnot(lon_avg).and.mpl%msv%isnot(lat_avg) &
 & .and.mpl%msv%isnot(proc_to_lon(iproc)).and.mpl%msv%isnot(proc_to_lat(iproc))) then
         ! Compute distance
         call sphere_dist(lon_avg,lat_avg,proc_to_lon(iproc),proc_to_lat(iproc),dist)

         ! Check distance
         if (inf(dist,dist_max+proc_to_dist_max(iproc)+nam%universe_radius)) geom%myuniverse(iproc) = .true.
      end if
   end do

   ! Release memory
   deallocate(proc_to_lon)
   deallocate(proc_to_lat)
   deallocate(proc_to_dist_max)
end if

! Share universe size
call mpl%f_comm%allgather(count(geom%myuniverse),proc_to_universe_size)

! Compute universe area
proc_to_universe_proportion = real(proc_to_universe_size,kind_real)/real(count(geom%proc_to_nc0a>0),kind_real)
geom%universe_proportion = proc_to_universe_proportion(mpl%myproc)

! Print results
call mpl%flush
do iproc=1,mpl%nproc
   write(mpl%info,'(a10,a,i6,a,f6.2,a)') '','Task ',iproc,': ',hundred*proc_to_universe_proportion(iproc),'%'
   call mpl%flush
end do

! Communicate data from halo A to universe on subset Sc0
write(mpl%info,'(a10,a)') '','Communicate data from halo A to universe on subset Sc0'
call mpl%flush

! Subset Sc0 universe size
geom%nc0u = sum(geom%proc_to_nc0a,mask=geom%myuniverse)

! Allocation
allocate(geom%proc_to_nc0u(mpl%nproc))

! Communication
call mpl%f_comm%allgather(geom%nc0u,geom%proc_to_nc0u)

! Check universe size
if ((geom%nc0a>0).and.(geom%nc0a<geom%nc0).and.(geom%nc0u==geom%nc0a)) &
 & call mpl%abort('${subr}$','universe is not larger than halo A')

! Allocation
allocate(geom%c0a_to_c0u(geom%nc0a))
allocate(geom%c0u_to_c0a(geom%nc0u))
allocate(geom%c0u_to_c0(geom%nc0u))
allocate(geom%lon_c0u(geom%nc0u))
allocate(geom%lat_c0u(geom%nc0u))
allocate(geom%vert_coord_c0u(geom%nc0u,geom%nl0))
allocate(geom%gmask_c0u(geom%nc0u,geom%nl0))
allocate(geom%gmask_hor_c0u(geom%nc0u))
allocate(order(geom%nc0u))

! Conversions
geom%c0u_to_c0a = mpl%msv%vali
ic0u = 0
do ic0=1,geom%nc0
   iproc = geom%c0_to_proc(ic0)
   if (geom%myuniverse(iproc)) then
      ic0u = ic0u+1
      if (iproc==mpl%myproc) then
         ic0a = geom%c0_to_c0a(ic0)
         geom%c0a_to_c0u(ic0a) = ic0u
         geom%c0u_to_c0a(ic0u) = ic0a
      end if
      geom%c0u_to_c0(ic0u) = ic0
   end if
end do

! Setup subset Sc0 communication, local to universe
call geom%com_AU%setup(mpl,'com_AU',geom%nc0a,geom%nc0u,geom%nc0,geom%c0a_to_c0,geom%c0u_to_c0)

! Extend fields from halo A to universe on subset Sc0
call geom%com_AU%ext(mpl,geom%lon_c0a,geom%lon_c0u)
call geom%com_AU%ext(mpl,geom%lat_c0a,geom%lat_c0u)
call geom%com_AU%ext(mpl,geom%vert_coord_c0a,geom%vert_coord_c0u)
call geom%com_AU%ext(mpl,geom%gmask_c0a,geom%gmask_c0u)
if (geom%nc0u>0) geom%gmask_hor_c0u = any(geom%gmask_c0u,dim=2)

! Check that Sc0 points in universe are not duplicated
write(mpl%info,'(a7,a)') '','Check that Sc0 points in universe are not duplicated'
call mpl%flush
call qsort(geom%nc0u,geom%lon_c0u,geom%lat_c0u,order,.false.)
do ic0u=2,geom%nc0u
   if (indist(geom%lat_c0u(order(ic0u)),geom%lat_c0u(order(ic0u-1)))) then
      if (indist(geom%lat_c0u(order(ic0u)),half*pi)) then
         call mpl%abort('${subr}$','duplicated points at the North pole')
      else if (indist(geom%lat_c0u(order(ic0u)),-half*pi)) then
         call mpl%abort('${subr}$','duplicated points at the South pole')
      else if (eq(geom%lon_c0u(order(ic0u)),geom%lon_c0u(order(ic0u-1)))) then
         call mpl%abort('${subr}$','duplicated points in Sc0 point on universe, check the universe')
      end if
   end if
end do

! Release memory
deallocate(order)

end subroutine geom_setup_universe

!----------------------------------------------------------------------
! Subroutine: geom_setup_hulls
!> Setup universe and full domain hulls
!----------------------------------------------------------------------
subroutine geom_setup_hulls(geom,mpl,rng,nam)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom !< Geometry
type(mpl_type),intent(inout) :: mpl    !< MPI data
type(rng_type),intent(inout) :: rng    !< Random number generator
type(nam_type),intent(in) :: nam       !< Namelist

! Local variables
integer :: ib,i,iproc,nba,ic0u,ic0a,nb,iba
integer :: proc_to_nba(mpl%nproc),displs(mpl%nproc)
real(kind_real),allocatable :: vbnd(:,:),lon_bnda(:),lat_bnda(:),lon_bnd(:),lat_bnd(:)
type(mesh_type) :: mesh_bnd

! Set name
@:set_name(geom_setup_hulls)

! Universe hull
if (geom%nc0u>0) then
   ! Allocation
   allocate(vbnd(3,geom%mesh_c0u%nb))

   ! Copy mesh boundary points
   do ib=1,geom%mesh_c0u%nb
      i = geom%mesh_c0u%bnodes(ib)
      vbnd(:,ib) = (/geom%mesh_c0u%x(i),geom%mesh_c0u%y(i),geom%mesh_c0u%z(i)/)
   end do

   ! Setup hull
   if (geom%deprecated_hull) then
      if (geom%global.and.indist(geom%universe_proportion,one)) then
         call geom%hull_c0u%init(mpl)
      else
         call geom%hull_c0u%init(mpl,geom%nc0u,geom%lon_c0u,geom%lat_c0u,nam%universe_radius)
      end if
   else
      call geom%hull_c0u%init(geom%mesh_c0u%nb,vbnd)
   end if

   ! Release memory
   deallocate(vbnd)
end if

! Full domain hull
if (geom%global) then
   ! Whole sphere
   call geom%hull_c0%init(mpl)
else
   ! Count local boundary points
   nba = 0
   do ib=1,geom%mesh_c0u%nb
      ic0u = geom%mesh_c0u%order(geom%mesh_c0u%bnodes(ib))
      ic0a = geom%c0u_to_c0a(ic0u)
      if (mpl%msv%isnot(ic0a)) nba = nba+1
   end do

   ! Gather number of local boundary points
   call mpl%f_comm%allgather(nba,proc_to_nba)

   ! Total number of boundary points
   nb = sum(proc_to_nba)
   if (nb==0) call mpl%abort('${subr}$','no boundary points for a regional domain')

   ! Allocation
   allocate(lon_bnda(nba))
   allocate(lat_bnda(nba))
   allocate(lon_bnd(nb))
   allocate(lat_bnd(nb))

   ! Copy potential boundary points
   iba = 0
   do ib=1,geom%mesh_c0u%nb
      ic0u = geom%mesh_c0u%order(geom%mesh_c0u%bnodes(ib))
      ic0a = geom%c0u_to_c0a(ic0u)
      if (mpl%msv%isnot(ic0a)) then
         iba = iba+1
         lon_bnda(iba) = geom%lon_c0a(ic0a)
         lat_bnda(iba) = geom%lat_c0a(ic0a)
      end if
   end do

   ! Gather local boundary points
   displs(1) = 0
   do iproc=2,mpl%nproc
      displs(iproc) = displs(iproc-1)+proc_to_nba(iproc-1)
   end do
   call mpl%f_comm%allgather(lon_bnda,lon_bnd,proc_to_nba(mpl%myproc),proc_to_nba,displs)
   call mpl%f_comm%allgather(lat_bnda,lat_bnd,proc_to_nba(mpl%myproc),proc_to_nba,displs)

   ! Create mesh with boundary points
   call mesh_bnd%init(mpl,rng,nb,lon_bnd,lat_bnd)

   ! Allocation
   allocate(vbnd(3,mesh_bnd%nb))

   ! Copy mesh boundary points
   do ib=1,mesh_bnd%nb
      i = mesh_bnd%bnodes(ib)
      vbnd(:,ib) = (/mesh_bnd%x(i),mesh_bnd%y(i),mesh_bnd%z(i)/)
   end do

   ! Setup hull
   call geom%hull_c0%init(mesh_bnd%nb,vbnd)

   ! Release memory
   deallocate(lon_bnda)
   deallocate(lat_bnda)
   deallocate(lon_bnd)
   deallocate(lat_bnd)
   deallocate(vbnd)
end if

! Reset random seed if necessary
call rng%reseed

end subroutine geom_setup_hulls

!----------------------------------------------------------------------
! Subroutine: geom_setup_grid
!> Setup grid properties
!----------------------------------------------------------------------
subroutine geom_setup_grid(geom,mpl,rng)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom !< Geometry
type(mpl_type),intent(inout) :: mpl    !< MPI data
type(rng_type),intent(inout) :: rng    !< Random number generator

! Local variables
integer :: il0,ic0a,ib,iprocmax,icorner,ib_1,ib_2,ib_3,nc0_inside,iter,i,iproc
integer :: imga,nmg_inside,nmg_owned
real(kind_real) :: infl,dinfl,infl_opt,f_min
real(kind_real) :: north,south,east,west
real(kind_real) :: proc_to_maxdist(mpl%nproc)
real(kind_real) :: dist,maxdist,splon_opt,splat_opt,rota_opt,dist_maxmin
real(kind_real) :: lonlat_bnd(2,4),v_bnd(3,4),v1(3),v2(3),cp(3),cd(3),v_bnd_infl(3,4),vtmp(3)
real(kind_real) :: lonlat_bnd_opt(2,4)
real(kind_real) :: norm_c0(geom%nl0),vert_coord_hor_c0(geom%nl0)
real(kind_real) :: area_124,area_234
real(kind_real),allocatable :: v_c0a(:,:)
logical :: valid
type(atlas_functionspace_structuredcolumns) :: afunctionspace_sc
type(atlas_config) :: aconfig_domain,aconfig_work_proj
type(atlas_structuredgrid) :: agrid_work
type(hull_type) :: hull
type(minim_type) :: minim
character(len=:),allocatable :: domain_type

! Set name
@:set_name(geom_setup_grid)

! Get area from hull
geom%area = geom%hull_c0%area

if (geom%global) then
   ! Global domain

   ! Arbitrary center
   geom%v_center = (/one,zero,zero/)
else
   ! Regional domain

   ! Allocation
   allocate(v_c0a(3,geom%nc0a))

   ! Convert to cartesian coordinates
   do ic0a=1,geom%nc0a
      call lonlat2xyz(mpl,geom%lon_c0a(ic0a),geom%lat_c0a(ic0a),v_c0a(1,ic0a),v_c0a(2,ic0a),v_c0a(3,ic0a))
   end do

   ! Find domain centroid
   geom%v_center = sum(v_c0a,dim=2)
   call mpl%f_comm%allreduce(geom%v_center,fckit_mpi_sum())
   geom%v_center = geom%v_center/sqrt(sum(geom%v_center**2))

   if ((geom%afunctionspace_mg%name()=='StructuredColumns').and.(.not.geom%deprecated_work_grid)) then
      ! Get StructuredColumns function space
      afunctionspace_sc = geom%afunctionspace_mg

      ! Get work grid
      agrid_work = afunctionspace_sc%grid()

      ! Get work grid configuration
      geom%aconfig_work_grid = agrid_work%spec()
   else
      ! Find the point furthest from the centroid (first corner)
      maxdist = zero
      do ic0a=1,geom%nc0a
         dist = sum((v_c0a(:,ic0a)-geom%v_center)**2)
         if (sup(dist,maxdist)) then
            maxdist = dist
            vtmp = v_c0a(:,ic0a)
         end if
      end do
      call mpl%f_comm%allgather(maxdist,proc_to_maxdist)
      iprocmax = 1
      do iproc=1,mpl%nproc
         if (sup(proc_to_maxdist(iproc),proc_to_maxdist(iprocmax))) iprocmax = iproc
      end do
      call mpl%f_comm%broadcast(vtmp,iprocmax-1)
      v_bnd(:,1) = vtmp

      ! Find the point furthest from the first corner (opposite corner)
      maxdist = zero
      do ic0a=1,geom%nc0a
         dist = sum((v_c0a(:,ic0a)-v_bnd(:,1))**2)
         if (sup(dist,maxdist)) then
            maxdist = dist
            vtmp = v_c0a(:,ic0a)
         end if
      end do
      call mpl%f_comm%allgather(maxdist,proc_to_maxdist)
      iprocmax = 1
      do iproc=1,mpl%nproc
         if (sup(proc_to_maxdist(iproc),proc_to_maxdist(iprocmax))) iprocmax = iproc
      end do
      call mpl%f_comm%broadcast(vtmp,iprocmax-1)
      v_bnd(:,3) = vtmp

      ! Find the two other corners
      do icorner=1,2
         ! Index
         ib_1 = 2*icorner-1
         ib_2 = 2*icorner
         ib_3 = 2*icorner+1
         if (ib_3>4) ib_3 = ib_3-4

         ! Get positive triangle with maximum area
         maxdist = zero
         do ic0a=1,geom%nc0a
            ! Check points order
            v1 = v_c0a(:,ic0a)-v_bnd(:,ib_1)
            v2 = v_bnd(:,ib_3)-v_bnd(:,ib_1)
            call vector_product(v1,v2,cp)
            cd = (v_bnd(:,ib_1)+v_c0a(:,ic0a)+v_bnd(:,ib_3))/three
            if (sup(sum(cp*cd),zero)) then
               ! Compute area
               call area(v_bnd(:,ib_1),v_c0a(:,ic0a),v_bnd(:,ib_3),dist)
               if (sup(dist,maxdist)) then
                  maxdist = dist
                  vtmp = v_c0a(:,ic0a)
               end if
            end if
         end do
         call mpl%f_comm%allgather(maxdist,proc_to_maxdist)
         iprocmax = 1
         do iproc=1,mpl%nproc
            if (sup(proc_to_maxdist(iproc),proc_to_maxdist(iprocmax))) iprocmax = iproc
         end do
         call mpl%f_comm%broadcast(vtmp,iprocmax-1)
         v_bnd(:,ib_2) = vtmp
      end do

      if (geom%deprecated_hull) then
         ! Compute area

         ! Compute area as the sum of two spherical triangles
         call area(v_bnd(:,1),v_bnd(:,2),v_bnd(:,4),area_124)
         call area(v_bnd(:,2),v_bnd(:,3),v_bnd(:,4),area_234)
         geom%area = area_124+area_234

         ! Create hull
         call hull%init(4,v_bnd)

         ! Count points inside hull
         nmg_inside = 0
         do imga=1,geom%nmga
            if (geom%owned_mga(imga,1)) then
               call hull%inside(mpl,geom%lon_mga(imga),geom%lat_mga(imga),valid)
              if (valid) nmg_inside = nmg_inside+1
            end if
         end do
         call mpl%f_comm%allreduce(nmg_inside,fckit_mpi_sum())

         ! Adjust area
         call mpl%f_comm%allreduce(count(geom%owned_mga),nmg_owned,fckit_mpi_sum())
         geom%area = geom%area*real(nmg_owned,kind_real)/real(nmg_inside,kind_real)

         ! Release memory
         call hull%dealloc
      end if

      ! Inflate corners from centers to include all points

      ! Optimize inflation with a dichotomy method
      geom%v_center = sum(v_bnd,dim=2)/four
      geom%v_center = geom%v_center/sqrt(sum(geom%v_center**2))
      infl = one
      dinfl = one
      do iter=1,niter
         ! Inflation factor
         infl = infl+dinfl

         ! Inflated corners
         do ib=1,4
            v_bnd_infl(:,ib) = geom%v_center+infl*(v_bnd(:,ib)-geom%v_center)
            v_bnd_infl(:,ib) = v_bnd_infl(:,ib)/sqrt(sum(v_bnd_infl(:,ib)**2))
         end do

         ! Create hull
         call hull%init(4,v_bnd_infl)

         ! Count points inside hull
         nc0_inside = 0
         do ic0a=1,geom%nc0a
            call hull%inside(mpl,geom%lon_c0a(ic0a),geom%lat_c0a(ic0a),valid)
            if (valid) nc0_inside = nc0_inside+1
         end do
         call mpl%f_comm%allreduce(nc0_inside,fckit_mpi_sum())

         ! Release memory
         call hull%dealloc

         if (nc0_inside==geom%nc0) then
            ! Reduce inflation
            dinfl = -half*abs(dinfl)
            infl_opt = infl
         else
            ! Increase inflation
            dinfl = half*dinfl
         end if
      end do

      ! Apply optimal inflation
      do ib=1,4
         v_bnd(:,ib) = geom%v_center+infl_opt*(v_bnd(:,ib)-geom%v_center)
         v_bnd(:,ib) = v_bnd(:,ib)/sqrt(sum(v_bnd(:,ib)**2))
      end do

      ! Convert to spherical coordinates
      do ib=1,4
         call xyz2lonlat(mpl,v_bnd(1,ib),v_bnd(2,ib),v_bnd(3,ib),lonlat_bnd(1,ib),lonlat_bnd(2,ib))
      end do

      ! Compute work grid

      ! Minimization parameters initialization
      minim%hooke_rho = half
      minim%hooke_tol = 1.0e-6_kind_real
      if (geom%deprecated_hull) then
         minim%hooke_itermax = 25
      else
         minim%hooke_itermax = 15
      end if

      ! Allocation
      minim%nx = 3
      minim%ny = 8
      call minim%alloc

      ! Guess and bounds
      minim%binf(1) = -pi
      minim%bsup(1) = pi
      minim%binf(2) = -half*pi
      minim%bsup(2) = half*pi
      minim%binf(3) = -pi
      minim%bsup(3) = pi

      ! Observations
      minim%obs = reshape(lonlat_bnd,(/8/))

      ! Fit type
      minim%cost_function = 'work_grid'
      f_min = huge_real

      if (geom%deprecated_hull) then
         ! Reseed for backward compatibility
         call rng%reseed
         rng%seed = rng%seed+1
      end if

      ! Resynchronize random number generator
      call rng%resync(mpl)

      do iter=1,10
         ! Random guess
         do i=1,3
            call rng%rand(minim%binf(i),minim%bsup(i),minim%guess(i))
         end do

         ! Compute fit
         call minim%compute(mpl)

         if (minim%f_min<f_min) then
            ! Get parameter, apply bounds
            splon_opt = max(minim%binf(1),min(minim%x(1),minim%bsup(1)))
            splat_opt = max(minim%binf(2),min(minim%x(2),minim%bsup(2)))
            rota_opt = max(minim%binf(3),min(minim%x(3),minim%bsup(3)))
            f_min = minim%f_min
         end if
      end do

      ! Desynchronize random number generator
      call rng%resync(mpl)

      ! Release memory
      call minim%dealloc

      ! Get work grid parameters
      call work_grid(splon_opt,splat_opt,rota_opt,lonlat_bnd,dist_maxmin,lonlat_bnd_opt,geom%aconfig_work_grid)

      ! Print results
      write(mpl%info,'(a7,a,e10.3,a)') '','Work regional grid accuracy: ',dist_maxmin*reqkm,' km'
      call mpl%flush
      do ib=1,4
         write(mpl%info,'(a10,a,i1.1,a,e10.3,a,e10.3,a,e10.3,a,e10.3,a)') '','Corner #',ib,': ', lonlat_bnd(1,ib)*rad2deg,' (', &
 & lonlat_bnd_opt(1,ib)*rad2deg,')  / ',lonlat_bnd(2,ib)*rad2deg,' (',lonlat_bnd_opt(2,ib)*rad2deg,')'
         call mpl%flush
      end do

      ! Extend work grid to make sure all points are included
      if (.not.geom%aconfig_work_grid%get('north',north)) call mpl%abort('${subr}$','missing north')
      if (.not.geom%aconfig_work_grid%get('south',south)) call mpl%abort('${subr}$','missing south')
      if (.not.geom%aconfig_work_grid%get('east',east)) call mpl%abort('${subr}$','missing east')
      if (.not.geom%aconfig_work_grid%get('west',west)) call mpl%abort('${subr}$','missing west')
      call geom%aconfig_work_grid%set('north',north+dist_maxmin*rad2deg)
      call geom%aconfig_work_grid%set('south',south-dist_maxmin*rad2deg)
      call geom%aconfig_work_grid%set('east',east+dist_maxmin*rad2deg)
      call geom%aconfig_work_grid%set('west',west-dist_maxmin*rad2deg)
   end if

   ! Add work grid domain
   agrid_work = atlas_structuredgrid(geom%aconfig_work_grid)
   geom%aconfig_work_grid = agrid_work%spec()
   if (.not.geom%aconfig_work_grid%get('domain',aconfig_domain)) call mpl%abort('${subr}$','missing domain')

   ! Get grid domain
   if (.not.aconfig_domain%get('type',domain_type)) call mpl%abort('${subr}$','missing domain type')
   if (trim(domain_type)/='rectangular') call mpl%abort('${subr}$','only rectangular domains allowed')
   if (.not.aconfig_domain%get('xmin',geom%xmin)) call mpl%abort('${subr}$','missing domain xmin')
   if (.not.aconfig_domain%get('xmax',geom%xmax)) call mpl%abort('${subr}$','missing domain xmax')
   if (.not.aconfig_domain%get('ymin',geom%ymin)) call mpl%abort('${subr}$','missing domain ymin')
   if (.not.aconfig_domain%get('ymax',geom%ymax)) call mpl%abort('${subr}$','missing domain ymax')

   ! Get grid projection
   if (.not.geom%aconfig_work_grid%get('projection',aconfig_work_proj)) call mpl%abort('${subr}$','missing projection')
   geom%aproj_work = atlas_projection(aconfig_work_proj)

   ! Release memory
   deallocate(v_c0a)
end if

! Miscellanous area-related fields
if (geom%nc0_gmask(0)>0) then
   geom%area_max_c0 = geom%area*real(count(geom%gmask_hor_c0a),kind_real)/real(geom%nc0,kind_real)
else
   geom%area_max_c0 = zero
end if
do il0=1,geom%nl0
   norm_c0(il0) = zss_count(geom%gmask_c0a(:,il0))
   if (norm_c0(il0)>0) then
      geom%area_ver_c0(il0) = geom%area*real(count(geom%gmask_c0a(:,il0)),kind_real)/real(geom%nc0,kind_real)
      vert_coord_hor_c0(il0) = zss_sum(geom%vert_coord_c0a(:,il0),mask=geom%gmask_c0a(:,il0))
   else
      geom%area_ver_c0(il0) = zero
      vert_coord_hor_c0(il0) = zero
   end if
end do
call mpl%f_comm%allreduce(norm_c0,fckit_mpi_sum())
call mpl%f_comm%allreduce(geom%area_max_c0,fckit_mpi_sum())
call mpl%f_comm%allreduce(geom%area_ver_c0,fckit_mpi_sum())
call mpl%f_comm%allreduce(vert_coord_hor_c0,fckit_mpi_sum())
do il0=1,geom%nl0
   if (norm_c0(il0)>0) then
      geom%vert_coordavg(il0) = vert_coord_hor_c0(il0)/real(norm_c0(il0),kind_real)
   else
      geom%vert_coordavg(il0) = mpl%msv%valr
   end if
end do

! Compute independent levels
write(mpl%test,'(a7,a)') '','Independent levels: '
call mpl%flush(newl=.false.)
call independent_levels(mpl,geom%nc0a,geom%nl0,geom%gmask_c0a,geom%nl0i,geom%l0_to_l0i,geom%l0i_to_l0)

! Reset random seed if necessary
call rng%reseed

end subroutine geom_setup_grid

!----------------------------------------------------------------------
! Subroutine: geom_lonlat_to_c0
!> Get nearest neighbor properties from longitude/latitude/level
!----------------------------------------------------------------------
subroutine geom_lonlat_to_c0(geom,mpl,n,lon,lat,il0,iproc,ic0a,lon_c0,lat_c0,mask_c0)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom               !< Geometry
type(mpl_type),intent(inout) :: mpl               !< MPI data
integer,intent(in) :: n                           !< Vector size
real(kind_real),intent(in) :: lon(n)              !< Longitudes
real(kind_real),intent(in) :: lat(n)              !< Latitudes
integer,intent(in) :: il0(n)                      !< Level indices
integer,intent(out),optional :: iproc(n)          !< Task indices
integer,intent(out),optional :: ic0a(n)           !< Local indices on Sc0, halo A
real(kind_real),intent(out),optional :: lon_c0(n) !< Longitudes
real(kind_real),intent(out),optional :: lat_c0(n) !< Latitudes
logical,intent(out),optional :: mask_c0(n)        !< Output mask

! Local variables
integer :: i
integer :: lic0a(n),liproc(n),ic0(n),imask(n)
real(kind_real) :: llon_c0(n),llat_c0(n)

! Set name
@:set_name(geom_lonlat_to_c0)

if (mpl%main) then
   do i=1,n
      ! Find nearest neighbor
      call geom%tree_c0%find_nearest_neighbors(mpl,lon(i),lat(i),1,ic0(i:i))

      ! Find corresponding task
      liproc(i) = geom%c0_to_proc(ic0(i))
   end do
end if

! Broadcast task
call mpl%f_comm%broadcast(liproc,mpl%rootproc-1)

! Copy if necessary
if (present(iproc)) iproc = liproc

if (present(ic0a).or.(present(lon_c0).and.present(lat_c0)).or.present(mask_c0)) then
   ! Broadcast index
   call mpl%f_comm%broadcast(ic0,mpl%rootproc-1)

   ! Get local values
   do i=1,n
      if (liproc(i)==mpl%myproc) then
         lic0a(i) = geom%c0_to_c0a(ic0(i))
         if (il0(i)==0) then
            call convert_l2i(geom%gmask_hor_c0a(lic0a(i)),imask(i))
         else
            call convert_l2i(geom%gmask_c0a(lic0a(i),il0(i)),imask(i))
         end if
         llon_c0(i) = geom%lon_c0a(lic0a(i))
         llat_c0(i) = geom%lat_c0a(lic0a(i))
      else
         lic0a(i) = mpl%msv%vali
         imask(i) = 0
         llon_c0(i) = zero
         llat_c0(i) = zero
      end if
   end do

   ! Reduce and copy if necessary
   if (present(ic0a)) ic0a = lic0a
   if (present(lon_c0).and.present(lat_c0)) then
      call mpl%f_comm%allreduce(llon_c0,fckit_mpi_sum())
      call mpl%f_comm%allreduce(llat_c0,fckit_mpi_sum())
      lon_c0 = llon_c0
      lat_c0 = llat_c0
   end if
   if (present(mask_c0)) then
      call mpl%f_comm%allreduce(imask,fckit_mpi_sum())
      do i=1,n
         call convert_i2l(mpl,imask(i),mask_c0(i))
      end do
   end if
end if

end subroutine geom_lonlat_to_c0

!----------------------------------------------------------------------
! Subroutine: geom_setup_dirac
!> Setup dirac indices
!----------------------------------------------------------------------
subroutine geom_setup_dirac(geom,mpl,nam)

implicit none

! Passed variables
class(geom_type),intent(inout) :: geom !< Geometry
type(mpl_type),intent(inout) :: mpl    !< MPI data
type(nam_type),intent(in) :: nam       !< Namelist

! Local variables
integer :: idir,il0,ic0a,idir_2d,ndir_2d,jl0
integer,allocatable :: nn_index(:),order(:,:),inbdir(:),idir_2dto3d(:)
real(kind_real),allocatable :: distv(:),londir_2d(:),latdir_2d(:)
logical :: maskdir(nam%ndir)
type(tree_type) :: tree_dirac

! Set name
@:set_name(geom_setup_dirac)

! Allocation
allocate(geom%inbdir(geom%nc0a,geom%nl0))

! Initialization
geom%inbdir = mpl%msv%vali

if (nam%check_dirac.and.(nam%ndir>0)) then
   write(mpl%info,'(a7,a)') '','Setup Dirac parameters'
   call mpl%flush

   ! Allocation
   geom%ndir = nam%ndir
   allocate(geom%londir(geom%ndir))
   allocate(geom%latdir(geom%ndir))
   allocate(geom%iprocdir(geom%ndir))
   allocate(geom%ic0adir(geom%ndir))
   allocate(geom%il0dir(geom%ndir))
   allocate(geom%ivdir(geom%ndir))

   ! Find level
   do idir=1,nam%ndir
      geom%il0dir(idir) = mpl%msv%vali
      do il0=1,geom%nl0
         if (il0==nam%levdir(idir)) geom%il0dir(idir) = il0
      end do
      if (mpl%msv%is(geom%il0dir(idir))) call mpl%abort('${subr}$','impossible to find the Dirac level')
   end do

   ! Index from lon/lat/level
   call geom%lonlat_to_c0(mpl,nam%ndir,nam%londir,nam%latdir,geom%il0dir,iproc=geom%iprocdir, &
 & ic0a=geom%ic0adir,lon_c0=geom%londir,lat_c0=geom%latdir,mask_c0=maskdir)

   ! Check validity
   do idir=1,geom%ndir
      if (maskdir(idir)) call geom%hull_c0%inside(mpl,geom%londir(idir),geom%latdir(idir),maskdir(idir))
      if (.not.maskdir(idir)) call mpl%abort('${subr}$','Dirac point is masked or out of the domain')
   end do

   ! Variable
   geom%ivdir = nam%ivdir

   ! Horizontal affectation
   do il0=1,geom%nl0
      ! Get number of Dirac points for this level
      ndir_2d = count(geom%il0dir==il0)

      if (ndir_2d>0) then
         ! Allocation
         allocate(londir_2d(ndir_2d))
         allocate(latdir_2d(ndir_2d))
         allocate(nn_index(ndir_2d))
         allocate(idir_2dto3d(ndir_2d))

         ! Initialization
         idir_2d = 0
         do idir=1,geom%ndir
            if (geom%il0dir(idir)==il0) then
               idir_2d = idir_2d+1
               londir_2d(idir_2d) = geom%londir(idir)
               latdir_2d(idir_2d) = geom%latdir(idir)
               idir_2dto3d(idir_2d) = idir
            end if
         end do

         ! Setup tree
         call tree_dirac%init(mpl,ndir_2d,londir_2d,latdir_2d)

         ! Affect each horizontal point to a dirac point
         do ic0a=1,geom%nc0a
            call tree_dirac%find_nearest_neighbors(mpl,geom%lon_c0a(ic0a),geom%lat_c0a(ic0a),ndir_2d,nn_index)
            geom%inbdir(ic0a,il0) = idir_2dto3d(nn_index(1))
         end do

         ! Release memory
         deallocate(londir_2d)
         deallocate(latdir_2d)
         deallocate(nn_index)
         deallocate(idir_2dto3d)
         call tree_dirac%dealloc
      end if
   end do

   ! Allocation
   allocate(distv(geom%nl0))
   allocate(order(geom%nl0,geom%nl0))
   allocate(inbdir(geom%nl0))

   ! Compute vertical distances
   order = mpl%msv%vali
   do il0=1,geom%nl0
      if (all(geom%il0dir/=il0)) then
         do jl0=1,geom%nl0
            distv(jl0) = abs(geom%vert_coordavg(il0)-geom%vert_coordavg(jl0))
         end do
         call qsort(geom%nl0,distv,order(:,il0))
      end if
   end do

   ! Vertical affectation
   do ic0a=1,geom%nc0a
      ! Copy profile
      inbdir = geom%inbdir(ic0a,:)
      do il0=1,geom%nl0
         jl0 = 1
         do while(mpl%msv%is(geom%inbdir(ic0a,il0)))
            ! Affect point
            if (mpl%msv%isnot(inbdir(order(jl0,il0)))) geom%inbdir(ic0a,il0) = inbdir(order(jl0,il0))
            jl0 = jl0+1
         end do
      end do
   end do

   ! Release memory
   deallocate(distv)
   deallocate(order)
   deallocate(inbdir)
else
   ! No dirac
   geom%ndir = 0
end if

end subroutine geom_setup_dirac

#:for dtype in dtypes_irl
!----------------------------------------------------------------------
! Subroutine: geom_copy_c0a_to_mga_${dtype}$_single
!> Copy from subset Sc0 to model grid, halo A, single field
!----------------------------------------------------------------------
subroutine geom_copy_c0a_to_mga_${dtype}$_single(geom,mpl,fld_c0a,fld_mga)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom                         !< Geometry
type(mpl_type),intent(inout) :: mpl                         !< MPI data
${ftype[dtype]}$,intent(in) :: fld_c0a(geom%nc0a,geom%nl0)  !< Field on subset Sc0, halo A
${ftype[dtype]}$,intent(out) :: fld_mga(geom%nmga,geom%nl0) !< Field on model grid, halo A

! Local variables
integer :: ic0a,imga,il0
${ftype[dtype]}$ :: fld_c0a_masked(geom%nc0a,geom%nl0)

! Set name
@:set_name(geom_copy_c0a_to_mga_${dtype}$_single)

! Set masked values at missing value
do il0=1,geom%nl0
   do ic0a=1,geom%nc0a
      if (geom%gmask_c0a(ic0a,il0)) then
         fld_c0a_masked(ic0a,il0) = fld_c0a(ic0a,il0)
      else
         fld_c0a_masked(ic0a,il0) = mpl%${msv[dtype]}$
      end if
   end do
end do

if (geom%same_grid) then
   ! Same grid
   fld_mga = fld_c0a_masked
else
   ! Initialization
   fld_mga = ${zero[dtype]}$

   ! Copy from subset Sc0 to model grid
   do il0=1,geom%nl0
      do ic0a=1,geom%nc0a
         imga = geom%c0a_to_mga(ic0a)
         fld_mga(imga,il0) = fld_c0a(ic0a,il0)
      end do
   end do
end if

end subroutine geom_copy_c0a_to_mga_${dtype}$_single

!----------------------------------------------------------------------
! Subroutine: geom_copy_c0a_to_mga_${dtype}$_all
!> Copy from subset Sc0 to model grid, halo A, all fields
!----------------------------------------------------------------------
subroutine geom_copy_c0a_to_mga_${dtype}$_all(geom,mpl,nam,fld_c0a,fld_mga)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom                                !< Geometry
type(mpl_type),intent(inout) :: mpl                                !< MPI data
type(nam_type),intent(in) :: nam                                   !< Namelist
${ftype[dtype]}$,intent(in) :: fld_c0a(geom%nc0a,geom%nl0,nam%nv)  !< Field on subset Sc0, halo A
${ftype[dtype]}$,intent(out) :: fld_mga(geom%nmga,geom%nl0,nam%nv) !< Field on model grid, halo A

! Local variables
integer :: iv

! Set name
@:set_name(geom_copy_c0a_to_mga_${dtype}$_all)

do iv=1,nam%nv
   call geom%copy_c0a_to_mga(mpl,fld_c0a(:,:,iv),fld_mga(:,:,iv))
end do

end subroutine geom_copy_c0a_to_mga_${dtype}$_all

!----------------------------------------------------------------------
! Subroutine: geom_copy_mga_to_c0a_${dtype}$_single
!> Copy from model grid to subset Sc0, halo A, single field
!----------------------------------------------------------------------
subroutine geom_copy_mga_to_c0a_${dtype}$_single(geom,mpl,fld_mga,fld_c0a)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom                         !< Geometry
type(mpl_type),intent(inout) :: mpl                         !< MPI data
${ftype[dtype]}$,intent(in) :: fld_mga(geom%nmga,geom%nl0)  !< Field on model grid, halo A
${ftype[dtype]}$,intent(out) :: fld_c0a(geom%nc0a,geom%nl0) !< Field on subset Sc0, halo A

! Local variables
integer :: ic0a,imga,il0

! Set name
@:set_name(geom_copy_mga_to_c0a_${dtype}$_single)

if (geom%same_grid) then
   ! Same grid
   fld_c0a = fld_mga
else
   ! Copy from model grid to subset Sc0
   do il0=1,geom%nl0
      do ic0a=1,geom%nc0a
         imga = geom%c0a_to_mga(ic0a)
         fld_c0a(ic0a,il0) = fld_mga(imga,il0)
      end do
   end do
end if

! Set masked values at missing value
do il0=1,geom%nl0
   do ic0a=1,geom%nc0a
      if (.not.geom%gmask_c0a(ic0a,il0)) fld_c0a(ic0a,il0) = mpl%${msv[dtype]}$
   end do
end do

end subroutine geom_copy_mga_to_c0a_${dtype}$_single

!----------------------------------------------------------------------
! Subroutine: geom_copy_mga_to_c0a_${dtype}$_all
!> Copy from model grid to subset Sc0, halo A, all fields
!----------------------------------------------------------------------
subroutine geom_copy_mga_to_c0a_${dtype}$_all(geom,mpl,nam,fld_c0a,fld_mga)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom                                !< Geometry
type(mpl_type),intent(inout) :: mpl                                !< MPI data
type(nam_type),intent(in) :: nam                                   !< Namelist
${ftype[dtype]}$,intent(in) :: fld_mga(geom%nmga,geom%nl0,nam%nv)  !< Field on model grid, halo A
${ftype[dtype]}$,intent(out) :: fld_c0a(geom%nc0a,geom%nl0,nam%nv) !< Field on subset Sc0, halo A

! Local variables
integer :: iv

! Set name
@:set_name(geom_copy_mga_to_c0a_${dtype}$_all)

do iv=1,nam%nv
   call geom%copy_mga_to_c0a(mpl,fld_mga(:,:,iv),fld_c0a(:,:,iv))
end do

end subroutine geom_copy_mga_to_c0a_${dtype}$_all
#:endfor

!----------------------------------------------------------------------
! Subroutine: geom_fieldset_to_c0
!> Fieldset to Fortran array on subset Sc0
!----------------------------------------------------------------------
subroutine geom_fieldset_to_c0(geom,mpl,nam,fieldset,fld_c0a)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom                               !< Geometry
type(mpl_type),intent(inout) :: mpl                               !< MPI data
type(nam_type),intent(in) :: nam                                  !< Namelist
type(fieldset_type),intent(in) :: fieldset                        !< Fieldset
real(kind_real),intent(out) :: fld_c0a(geom%nc0a,geom%nl0,nam%nv) !< Field on subset Sc0, halo A

! Local variables
real(kind_real) :: fld_mga(geom%nmga,geom%nl0,nam%nv)

! Set name
@:set_name(geom_fieldset_to_c0)

if (geom%same_grid) then
   ! Fieldset to Fortran array on subset Sc0
   call fieldset%to_array(mpl,fld_c0a)
else
   ! Fieldset to Fortran array on model grid
   call fieldset%to_array(mpl,fld_mga)

   ! Model grid to subset Sc0
   call geom%copy_mga_to_c0a(mpl,nam,fld_c0a,fld_mga)
end if

end subroutine geom_fieldset_to_c0

!----------------------------------------------------------------------
! Subroutine: geom_c0_to_fieldset
!> Fortran array on subset Sc0 to fieldset
!----------------------------------------------------------------------
subroutine geom_c0_to_fieldset(geom,mpl,nam,fld_c0a,fieldset)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom                              !< Geometry
type(mpl_type),intent(inout) :: mpl                              !< MPI data
type(nam_type),intent(in) :: nam                                 !< Namelist
real(kind_real),intent(in) :: fld_c0a(geom%nc0a,geom%nl0,nam%nv) !< Field on subset Sc0, halo A
type(fieldset_type),intent(inout) :: fieldset                    !< Fieldset

! Local variables
real(kind_real),allocatable :: fld_mga(:,:,:)

! Set name
@:set_name(geom_c0_to_fieldset)

if (geom%same_grid) then
   ! Fortran array on subset Sc0 to fieldset
   call fieldset%from_array(mpl,fld_c0a)
else
   ! Allocation
   allocate(fld_mga(geom%nmga,geom%nl0,nam%nv))

   ! Subset Sc0 to model grid
   call geom%copy_c0a_to_mga(mpl,nam,fld_c0a,fld_mga)

   ! Fortran array on model grid to fieldset
   call fieldset%from_array(mpl,fld_mga)

   ! Release memory
   deallocate(fld_mga)
end if

end subroutine geom_c0_to_fieldset

!----------------------------------------------------------------------
! Subroutine: geom_rand_points
!> Select random valid point on the horizontal grid
!----------------------------------------------------------------------
subroutine geom_rand_points(geom,mpl,rng,n,il0,iproc,ic0a)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom !< Geometry
type(mpl_type),intent(inout) :: mpl !< MPI data
type(rng_type),intent(inout) :: rng !< Random number generator
integer,intent(in) :: n             !< Vector size
integer,intent(in) :: il0(n)        !< Levels
integer,intent(out) :: iproc(n)     !< Tasks
integer,intent(out) :: ic0a(n)      !< Local index

! Local variables
integer :: i
real(kind_real) :: x,y
real(kind_real) :: lon(1),lat(1)
logical :: valid(1)

! Set name
@:set_name(geom_rand_points)

! Resynchronize random number generator
call rng%resync(mpl)

! Initialization
i = 1

! Loop
do while (i<=n)
   ! Generate random lon/lat
   if (geom%global) then
      call rng%rand(-pi,pi,lon(1))
      call rng%rand(-one,one,lat(1))
      lat = asin(lat)
   else
      call rng%rand(zero,one,x)
      call rng%rand(zero,one,y)
      x = geom%xmin+x*(geom%xmax-geom%xmin)
      y = geom%ymin+y*(geom%ymax-geom%ymin)
      call geom%aproj_work%xy2lonlat(x,y,lon(1),lat(1))
      lon(1) = lon(1)*deg2rad
      lat(1) = lat(1)*deg2rad
   end if

   ! Get index from lon/lat
   call geom%lonlat_to_c0(mpl,1,lon,lat,il0(i:i),iproc=iproc(i:i),ic0a=ic0a(i:i),mask_c0=valid)
   if (valid(1)) call geom%hull_c0%inside(mpl,lon(1),lat(1),valid(1))

   ! Update index
   if (valid(1)) i = i+1
end do

! Desynchronize random number generator
call rng%desync(mpl)

end subroutine geom_rand_points

!----------------------------------------------------------------------
! Subroutine: geom_initialize_sampling_from_size
!> Intialize sampling from minimal size
!----------------------------------------------------------------------
subroutine geom_initialize_sampling_from_size(geom,mpl,ncx,tree_cx,mask_cx,fmask_cx,ifmt,ns,s_to_cx)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom             !< Geometry
type(mpl_type),intent(inout) :: mpl             !< MPI data
integer,intent(in) :: ncx                       !< Number of points (full domain)
type(tree_type),intent(in) :: tree_cx           !< KD-tree (full domain)
logical,intent(in) :: mask_cx(ncx)              !< Sampling mask (full domain)
logical,intent(in) :: fmask_cx(ncx)             !< Forced points mask (full domain)
integer,intent(in) :: ifmt                      !< Format indentation
integer,intent(inout) :: ns                     !< Number of samplings points, target as input (full domain)
integer,allocatable,intent(inout) :: s_to_cx(:) !< Horizontal sampling index (full domain)

! Local variables
integer :: nmin,ix,iy,icxeff,is,icx,hash
integer :: nn_index(1)
integer,allocatable :: order_s(:)
real(kind_real) :: lonlat(2)
real(kind_real),allocatable :: lon_s(:),lat_s(:)
logical,allocatable :: lmask_cx(:),gmask_s(:)
character(len=1024) :: cfmt
type(atlas_structuredgrid) :: agrid

! Set name
@:set_name(geom_initialize_sampling_from_size)

if (mpl%main) then
   ! Get grid based on size
   nmin = ns
   if (geom%global) then
      ! Global grid
      call get_grid(mpl,nmin,agrid,ns)
   else
      ! Regional grid
      call get_grid(mpl,nmin,geom%aconfig_work_grid,agrid,ns)
   end if

   ! Allocation
   allocate(lmask_cx(ncx))

   ! Loop over grid points
   lmask_cx = fmask_cx
   do iy=1,int(agrid%ny(),kind_int)
      do ix=1,int(agrid%nx(iy),kind_int)
         ! Get longitude/latitude
         lonlat = agrid%lonlat(ix,iy)*deg2rad
         call lonlatmod(lonlat(1),lonlat(2))

         ! Find nearest neighbor
         call tree_cx%find_nearest_neighbors(mpl,lonlat(1),lonlat(2),1,nn_index)
         icx = nn_index(1)

         ! Keep valid points on each task
         lmask_cx(icx) = .true.
      end do
   end do

   ! Release memory
   call agrid%final()

   ! Apply mask
   lmask_cx = lmask_cx.and.mask_cx

   ! Allocation
   ns = count(lmask_cx)
   allocate(s_to_cx(ns))

   ! Mapping from reduced to initial grid
   is = 0
   do icx=1,ncx
      if (lmask_cx(icx)) then
         is = is+1
         s_to_cx(is) = icx
      end if
   end do

   ! Release memory
   deallocate(lmask_cx)
end if

! Reorder points

! Broadcast
call mpl%f_comm%broadcast(ns,mpl%rootproc-1)

! Allocation
if (.not.mpl%main) allocate(s_to_cx(ns))
allocate(lon_s(ns))
allocate(lat_s(ns))
allocate(order_s(ns))
allocate(gmask_s(ns))

! Broadcast
call mpl%f_comm%broadcast(s_to_cx,mpl%rootproc-1)

if (mpl%main) then
   ! Define sampling coordinates
   do is=1,ns
      icx = s_to_cx(is)
      icxeff = tree_cx%to_eff(icx)
      lon_s(is) = tree_cx%lon(icxeff)
      lat_s(is) = tree_cx%lat(icxeff)
   end do
end if

! Broadcast sampling coordinates
call mpl%f_comm%broadcast(lon_s,mpl%rootproc-1)
call mpl%f_comm%broadcast(lat_s,mpl%rootproc-1)

! Define points order
call qsort(ns,lon_s,lat_s,order_s)

! Reorder sampling
s_to_cx = s_to_cx(order_s)

! Grid hash
gmask_s = .true.
call grid_hash(ns,lon_s,lat_s,gmask_s,hash)

! Test grid hash
write(cfmt,'(a,i2.2,a)') '(a',ifmt+3,',a,i12)'
write(mpl%test,trim(cfmt)) '','Subgrid hash: ',hash
if (ifmt>0) call mpl%flush

! Release memory
deallocate(lon_s)
deallocate(lat_s)
deallocate(order_s)
deallocate(gmask_s)

end subroutine geom_initialize_sampling_from_size

!----------------------------------------------------------------------
! Subroutine: geom_initialize_sampling_from_rad
!> Intialize sampling from radius
!----------------------------------------------------------------------
subroutine geom_initialize_sampling_from_rad(geom,mpl,rng,draw_type,rh_c0a,resol,ifmt,ns,lon_s,lat_s,s_to_c0)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom                  !< Geometry
type(mpl_type),intent(inout) :: mpl                  !< MPI data
type(rng_type),intent(inout) :: rng                  !< Random number generator
character(len=*),intent(in) :: draw_type             !< Draw type (regular or random)
real(kind_real),intent(in) :: rh_c0a(geom%nc0a)      !< Horizontal support radius (local)
real(kind_real),intent(in) :: resol                  !< Sampling resolution
integer,intent(in) :: ifmt                           !< Format indentation
integer,intent(out) :: ns                            !< Number of samplings points (full domain)
real(kind_real),allocatable,intent(inout) :: lon_s(:) !< Sampling longitudes (full domain)
real(kind_real),allocatable,intent(inout) :: lat_s(:) !< Sampling latitudes (full domain)
integer,allocatable,intent(inout) :: s_to_c0(:)       !< Sampling indices (full domain)

! Local variables
integer :: active_list_size,ir_base,ireg_base,id,ia,ireg_test,nn_test,i,ic0,is,hash,nreg,ireg,ix,iy,ns_nomask,is_nomask,is_base
integer :: nn_index(1),nn_index_check(2),order_a(na_bridson)
integer,allocatable :: s_nomask_to_c0(:),active_list(:),s_nomask_to_reg(:),grid_flag(:),nn_index_test(:),order_s(:)
real(kind_real) :: rh_min,rh_max,lgrid_factor,x,y,z,x_next,y_next,z_next,x_test,y_test,z_test,lon_test,lat_test,rh_test,rh
real(kind_real) :: x_base,y_base,z_base,lon_base,lat_base,rh_base,cos_lon_base,sin_lon_base,cos_lat_base,sin_lat_base
real(kind_real) :: dist,angle,cos_angle,sin_angle
real(kind_real) :: lonlat(2),nn_dist_check(2),angles(na_bridson),dists(nd_bridson)
real(kind_real),allocatable :: rh_c0(:),lon_reg(:),lat_reg(:),rh_reg(:),lon_s_nomask(:),lat_s_nomask(:),rh_s(:)
real(kind_real),allocatable :: nn_dist_test(:),nn_dist_eff(:),resol_eff(:)
logical :: found,valid
logical,allocatable :: mask_c0(:),mask_s(:),gmask_s(:)
character(len=1024) :: ldraw_type,cfmt
type(atlas_structuredgrid) :: agrid
type(tree_type) :: tree_reg,tree_s

! Set name
@:set_name(geom_initialize_sampling_from_rad)

! Get minimum/maximum support radius
call mpl%f_comm%allreduce(zss_minval(rh_c0a,mask=mpl%msv%isnot(rh_c0a)),rh_min,fckit_mpi_min())
call mpl%f_comm%allreduce(zss_maxval(rh_c0a,mask=mpl%msv%isnot(rh_c0a)),rh_max,fckit_mpi_max())

! Get local draw type
ldraw_type = draw_type
if (inf(rh_min,rh_max)) then
   ! Inhomogeneous rh_c0 field, the 'random' draw type is required
   ldraw_type = 'random'
end if

! Allocation
if (mpl%main) then
   allocate(mask_c0(geom%nc0))
   allocate(rh_c0(geom%nc0))
else
   allocate(mask_c0(0))
   allocate(rh_c0(0))
end if

! Communication
call mpl%loc_to_glb(geom%nc0a,geom%nc0,geom%c0a_to_c0,geom%gmask_hor_c0a,mask_c0)
call mpl%loc_to_glb(geom%nc0a,geom%nc0,geom%c0a_to_c0,rh_c0a,rh_c0)

! Print support radius stats
write(cfmt,'(a,i2.2,a)') '(a',ifmt+3,',a,e10.3,a,e10.3,a,e10.3,a)'
write(mpl%test,trim(cfmt)) '','Requested distance between points (min/max/avg): ', &
 & minval(rh_c0,mask=mpl%msv%isnot(rh_c0))/resol*reqkm,' km / ', &
 & maxval(rh_c0,mask=mpl%msv%isnot(rh_c0))/resol*reqkm,' km / ', &
 & (sum(rh_c0,mask=mpl%msv%isnot(rh_c0))/real(count(mpl%msv%isnot(rh_c0)),kind_real))/resol*reqkm,' km'
if (ifmt>0) call mpl%flush

if (mpl%main) then
   ! Fill masked points with minimum support radius
   rh_min = zss_minval(rh_c0,mask=mpl%msv%isnot(rh_c0))
   do ic0=1,geom%nc0
      if (.not.mask_c0(ic0)) rh_c0(ic0) = rh_min
   end do

   ! Get local grid factor
   lgrid_factor = grid_factor
   if (ldraw_type=='regular') lgrid_factor = one

   ! Transform support radius into disk radius     
   rh_c0 = rh_c0/resol
   rh_min = rh_min/(resol*lgrid_factor)

   ! Get grid based on minimum disk radius
   if (geom%global) then
      ! Global grid
      call get_grid(mpl,rh_min,agrid,nreg)
   else
      ! Regional grid
      call get_grid(mpl,rh_min,geom%aconfig_work_grid,agrid,nreg)
   end if

   ! Reduce number of grid points for regional grids
   if (.not.geom%global) then
      do iy=1,int(agrid%ny(),kind_int)
         ! Remove one point for each even row
         if (mod(iy,2)==0) nreg = nreg-1
      end do
   end if

   ! Allocation
   allocate(lon_reg(nreg))
   allocate(lat_reg(nreg))
   allocate(rh_reg(nreg))
   allocate(lon_s_nomask(nreg))
   allocate(lat_s_nomask(nreg))
   allocate(s_nomask_to_reg(nreg))

   ! Loop over grid points
   ireg = 0
   do iy=1,int(agrid%ny(),kind_int)
      do ix=1,int(agrid%nx(iy),kind_int)
         if (geom%global.or.(mod(iy,2)==1).or.((mod(iy,2)==0).and.(ix<int(agrid%nx(iy),kind_int)))) then
            ! Full domain index
            ireg = ireg+1

            ! Get longitude/latitude
            lonlat = agrid%lonlat(ix,iy)*deg2rad
            call lonlatmod(lonlat(1),lonlat(2))
            lon_reg(ireg) = lonlat(1)
            lat_reg(ireg) = lonlat(2)

            ! Shift points to get triangles
            if ((.not.geom%global).and.(mod(iy,2)==0).and.(ix<int(agrid%nx(iy),kind_int))) then
               ! Move towards the next point in the row
               call lonlat2xyz(mpl,lon_reg(ireg),lat_reg(ireg),x,y,z)
               lonlat = agrid%lonlat(ix+1,iy)*deg2rad
               call lonlat2xyz(mpl,lonlat(1),lonlat(2),x_next,y_next,z_next)
               x = half*(x+x_next)
               y = half*(y+y_next)
               z = half*(z+z_next)
               lon_reg(ireg) = lonlat(1)
               lat_reg(ireg) = lonlat(2)
               call xyz2lonlat(mpl,x,y,z,lon_reg(ireg),lat_reg(ireg))
            end if

            ! Find nearest neighbor
            call geom%tree_c0%find_nearest_neighbors(mpl,lon_reg(ireg),lat_reg(ireg),1,nn_index)
            ic0 = nn_index(1)

            ! Copy disk radius
            rh_reg(ireg) = rh_c0(ic0)
         end if
      end do
   end do

   ! Print result
   write(cfmt,'(a,i2.2,a)') '(a',ifmt+3,',a,i8,a)'
   write(mpl%test,trim(cfmt)) '','Regular sampling grid size: ',nreg,' points'
   if (ifmt>0) call mpl%flush

   ! Release memory
   call agrid%final()

   if (ldraw_type=='regular') then
      ! Uniform support radius
      ns_nomask = nreg
      lon_s_nomask = lon_reg
      lat_s_nomask = lat_reg
      do is_nomask=1,ns_nomask
         s_nomask_to_reg(is_nomask) = is_nomask
      end do
   elseif (ldraw_type=='random') then
      ! Initialize tree
      call tree_reg%init(mpl,nreg,lon_reg,lat_reg)

      ! Allocation
      allocate(active_list(nreg))
      allocate(grid_flag(nreg))

      ! Initialization
      ns_nomask = 1
      active_list_size = 1
      active_list = 0
      active_list(active_list_size) = ns_nomask
      s_nomask_to_reg = 0
      grid_flag = 0

      ! Arbitrary starting point
      if (rng%reset_seed) then
         ! Deterministic run, use the domain center
         x_test = geom%v_center(1)
         y_test = geom%v_center(2)
         z_test = geom%v_center(3)
      else
         ! Random run, use a random point
         call rng%rand(-one,one,x_test)
         call rng%rand(-one,one,y_test)
         call rng%rand(-one,one,z_test)
      end if
      call xyz2lonlat(mpl,x_test,y_test,z_test,lon_test,lat_test)
      call tree_reg%find_nearest_neighbors(mpl,lon_test,lat_test,1,nn_index)
      ireg_test = nn_index(1)
      lon_s_nomask(ns_nomask) = tree_reg%lon(ireg_test)
      lat_s_nomask(ns_nomask) = tree_reg%lat(ireg_test)
      s_nomask_to_reg(ns_nomask) = ireg_test
      grid_flag(ireg_test) = ns_nomask

      ! Distances list
      do id=1,nd_bridson
         dists(id) = one+real(id-1,kind_real)/real(nd_bridson-1,kind_real)+repro_th
      end do

      ! Angles list
      do ia=1,na_bridson
         angles(ia) = two*pi*real(ia-1,kind_real)/real(na_bridson,kind_real)
      end do

      ! Loop while active list is not empty
      do while (active_list_size>0)
         ! Base sample
         call rng%rand(1,active_list_size,ir_base)
         is_base = active_list(ir_base)
         lon_base = lon_s_nomask(is_base)
         lat_base = lat_s_nomask(is_base)
         ireg_base = s_nomask_to_reg(is_base)
         rh_base = rh_reg(ireg_base)
         found = .false.

         ! Base sample coordinates
         cos_lon_base = cos(lon_base)
         sin_lon_base = sin(lon_base)
         cos_lat_base = cos(lat_base)
         sin_lat_base = sin(lat_base)
         call lonlat2xyz(mpl,lon_base,lat_base,x_base,y_base,z_base)

         ! Random shuffle for angles
         call rng%shuffle(na_bridson,order_a)

         ! Loop over distances/angles
         do id=1,nd_bridson
            do ia=1,na_bridson
               if (.not.found) then
                  ! Angle / distance
                  if (.false.) then
                     ! Really random (original Bridson's paper)
                     call rng%rand(zero,two*pi,angle)
                     call rng%rand(rh_base,two*rh_base,dist)
                  elseif (.false.) then
                     ! Shuffled positions (more accurate, but geometrical structures)
                     angle = angles(order_a(ia))
                     dist = dists(id)*rh_base
                  else
                     ! Hybrid solution (almost as accurate, no geometrical structures)
                     call rng%rand(zero,two*pi,angle)
                     dist = dists(id)*rh_base
                  end if
   
                  ! Modification of Bridson's method for the sphere
                  cos_angle = cos(angle)
                  sin_angle = sin(angle)
                  x_test = x_base+dist*(-sin_lon_base*cos_angle-sin_lat_base*cos_lon_base*sin_angle)
                  y_test = y_base+dist*(cos_lon_base*cos_angle-sin_lat_base*sin_lon_base*sin_angle)
                  z_test = z_base+dist*cos_lat_base*sin_angle
                  call xyz2lonlat(mpl,x_test,y_test,z_test,lon_test,lat_test)

                  ! Check if the sampled point is inside the domain
                  call geom%hull_c0%inside(mpl,lon_test,lat_test,valid)

                  if (valid) then
                      ! Find nearest neighbor on the regular grid
                      call tree_reg%find_nearest_neighbors(mpl,lon_test,lat_test,1,nn_index)
      
                     ! Test support radius
                     ireg_test = nn_index(1)
                     rh_test = rh_reg(ireg_test)
      
                     ! Find nearest neighbors
                     call tree_reg%find_nearest_neighbors(mpl,lon_test,lat_test,rh_test, &
 & nn_test,nn_index_test,nn_dist_test)
      
                     ! Check nearest neighbors
                     do i=1,nn_test
                        ireg = nn_index_test(i)
                        rh = sqrt(rh_reg(ireg)*rh_test)
                        if ((grid_flag(ireg)>0).and.inf(nn_dist_test(i),rh)) then
                          valid = .false.
                          exit
                        end if
                     end do
                     deallocate(nn_index_test)
      
                     if (valid) then
                        ns_nomask = ns_nomask+1
                        active_list_size = active_list_size+1
                        active_list(active_list_size) = ns_nomask
                        lon_s_nomask(ns_nomask) = lon_test
                        lat_s_nomask(ns_nomask) = lat_test
                        s_nomask_to_reg(ns_nomask) = ireg_test
                        grid_flag(ireg_test) = ns_nomask
                        found = .true.
                     end if
                  end if
               end if
            end do
         end do

         if (.not.found) then
            ! Remove base sample from active list
            active_list(ir_base:active_list_size-1) = active_list(ir_base+1:active_list_size)
            active_list_size = active_list_size-1
         end if
      end do

      ! Release memory
      deallocate(active_list)
      deallocate(grid_flag)
      call tree_reg%dealloc
   else
      ! Error message
      call mpl%abort('${subr}$','wrong sampling method: '//trim(ldraw_type))
   end if

   ! Allocation
   allocate(mask_s(ns_nomask))
   allocate(s_nomask_to_c0(ns_nomask))

   ! Detect masked points
   mask_s = .false.
   do is_nomask=1,ns_nomask
      ! Find nearest neighbor
      call geom%tree_c0%find_nearest_neighbors(mpl,lon_s_nomask(is_nomask),lat_s_nomask(is_nomask),1,nn_index)
      ic0 = nn_index(1)

      ! Copy index
      s_nomask_to_c0(is_nomask) = ic0

      ! Set mask
      mask_s(is_nomask) = mask_c0(ic0)
   end do

   ! Final sampling size
   ns = count(mask_s)

   ! Allocation
   if (allocated(lon_s)) deallocate(lon_s)
   if (allocated(lat_s)) deallocate(lat_s)
   allocate(lon_s(ns))
   allocate(lat_s(ns))
   allocate(rh_s(ns))
   allocate(s_to_c0(ns))
   allocate(nn_dist_eff(ns))
   allocate(resol_eff(ns))

   ! Copy sample
   is = 0
   do is_nomask=1,ns_nomask
      if (mask_s(is_nomask)) then
         is = is+1
         lon_s(is) = lon_s_nomask(is_nomask)
         lat_s(is) = lat_s_nomask(is_nomask)
         s_to_c0(is) = s_nomask_to_c0(is_nomask)
         ireg = s_nomask_to_reg(is_nomask)
         rh_s(is) = rh_reg(ireg)
      end if
   end do

   if (ifmt>0) then
      ! Build sampling tree
      call tree_s%init(mpl,ns,lon_s,lat_s)

      ! Find nearest neighbor for each sampling point
       do is=1,ns
         ! Get distance to the nearest neighbor
         call tree_s%find_nearest_neighbors(mpl,lon_s(is),lat_s(is),2,nn_index_check,nn_dist_check)
         if (nn_dist_check(1)>zero) call mpl%abort('{subr}','error in sampling')

         ! Get theoretical distance to the nearest neighbor
         nn_dist_eff(is) = nn_dist_check(2)*reqkm
         resol_eff(is) = resol*sqrt(rh_s(is)*rh_s(nn_index_check(2)))/nn_dist_check(2)
      end do

      ! Print results
      write(cfmt,'(a,i2.2,a)') '(a',ifmt+3,',a,e10.3,a,e10.3,a,e10.3,a)'
      write(mpl%test,trim(cfmt)) '','Nearest neighbor distance (min/max/avg): ',minval(nn_dist_eff),' km / ', &
 & maxval(nn_dist_eff),' km / ',sum(nn_dist_eff)/real(ns,kind_real),' km'
      call mpl%flush
      write(cfmt,'(a,i2.2,a)') '(a',ifmt+3,',a,f5.2,a,f5.2,a,f5.2)'
      write(mpl%test,trim(cfmt)) '','Effective resolution (min/max/avg): ',minval(resol_eff),' / ', &
 & maxval(resol_eff),' / ',sum(resol_eff)/real(ns,kind_real)
      call mpl%flush

   end if

   ! Release memory
   deallocate(nn_dist_eff)
   deallocate(resol_eff)
   deallocate(lon_reg)
   deallocate(lat_reg)
   deallocate(lon_s_nomask)
   deallocate(lat_s_nomask)
   deallocate(mask_s)
   deallocate(rh_reg)
   deallocate(rh_s)
   deallocate(s_nomask_to_reg)
   deallocate(s_nomask_to_c0)
end if

! Reorder points

! Broadcast
call mpl%f_comm%broadcast(ns,mpl%rootproc-1)

! Allocation
if (.not.mpl%main) then
   allocate(lon_s(ns))
   allocate(lat_s(ns))
   allocate(s_to_c0(ns))
end if
allocate(order_s(ns))
allocate(gmask_s(ns))

! Broadcast
call mpl%f_comm%broadcast(lon_s,mpl%rootproc-1)
call mpl%f_comm%broadcast(lat_s,mpl%rootproc-1)
call mpl%f_comm%broadcast(s_to_c0,mpl%rootproc-1)

! Define points order
call qsort(ns,lon_s,lat_s,order_s)

! Reorder sampling
s_to_c0 = s_to_c0(order_s)

! Grid hash
gmask_s = .true.
call grid_hash(ns,lon_s,lat_s,gmask_s,hash)

! Test grid hash
write(cfmt,'(a,i2.2,a)') '(a',ifmt+3,',a,i12)'
write(mpl%test,trim(cfmt)) '','Subgrid hash: ',hash
if (ifmt>0) call mpl%flush

! Release memory
deallocate(rh_c0)
deallocate(order_s)
deallocate(gmask_s)
call agrid%final()
call tree_s%dealloc

end subroutine geom_initialize_sampling_from_rad

!----------------------------------------------------------------------
! Subroutine: geom_define_test_vectors
!> Define test vectors
!----------------------------------------------------------------------
subroutine geom_define_test_vectors(geom,mpl,rng,nam,ntest,fld)

! Passed variables
class(geom_type),intent(in) :: geom                                 !< Geometry
type(mpl_type),intent(inout) :: mpl                                 !< MPI data
type(rng_type),intent(inout) :: rng                                 !< Random number generator
type(nam_type),intent(in) :: nam                                    !< Namelist
integer,intent(in) :: ntest                                         !< Number of vectors
real(kind_real),intent(out) :: fld(geom%nc0a,geom%nl0,nam%nv,ntest) !< Field

! Local variables
integer :: itest
integer :: il0dir(ntest),iprocdir(ntest),ic0adir(ntest)

! Set name
@:set_name(geom_define_test_vectors)

! Define random dirac levels
if (mpl%main) call rng%rand(1,geom%nl0,il0dir)
call mpl%f_comm%broadcast(il0dir,mpl%rootproc-1)

! Define random dirac location
call geom%rand_points(mpl,rng,ntest,il0dir,iprocdir,ic0adir)

do itest=1,ntest
   ! Define test vector
   fld(:,:,:,itest) = zero
   if (iprocdir(itest)==mpl%myproc) fld(ic0adir(itest),il0dir(itest),1,itest) = one
end do

! Reset random seed if necessary
call rng%reseed

end subroutine geom_define_test_vectors

!----------------------------------------------------------------------
! Function: geom_c0_to_c0a
!> Conversion from full domain to halo A on subset Sc0
!----------------------------------------------------------------------
function geom_c0_to_c0a(geom,ic0) result(ic0a)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom !< Geometry
integer,intent(in) :: ic0           !< Full domain index

! Returned variable
integer :: ic0a

! Set name
@:set_name(geom_c0_to_c0a)

! Call generic function
ic0a = cx_to_cxa(geom%nproc,geom%proc_to_c0_offset,ic0)

end function geom_c0_to_c0a

!----------------------------------------------------------------------
! Function: geom_c0_to_proc
!> Conversion from full domain to task on subset Sc0
!----------------------------------------------------------------------
function geom_c0_to_proc(geom,ic0) result(iproc)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom !< Geometry
integer,intent(in) :: ic0           !< Full domain index

! Returned variable
integer :: iproc

! Set name
@:set_name(geom_c0_to_proc)

! Call generic function
iproc = cx_to_proc(geom%nproc,geom%proc_to_c0_offset,ic0)

end function geom_c0_to_proc

!----------------------------------------------------------------------
! Function: geom_c0_to_c0u
!> Conversion from full domain to universe on subset Sc0
!----------------------------------------------------------------------
function geom_c0_to_c0u(geom,ic0) result(ic0u)

implicit none

! Passed variables
class(geom_type),intent(in) :: geom !< Geometry
integer,intent(in) :: ic0           !< Full domain index

! Returned variable
integer :: ic0u

! Set name
@:set_name(geom_c0_to_c0u)

! Call generic function
ic0u = cx_to_cxu(geom%nproc,geom%proc_to_c0_offset,geom%proc_to_nc0a,geom%myuniverse,ic0)

end function geom_c0_to_c0u

end module type_geom

