#:include 'generics.fypp'
!----------------------------------------------------------------------
! Module: type_hull
!> Hull derived type
! Author: Benjamin Menetrier
! Licensing: this code is distributed under the CeCILL-C license
! Copyright 2015-... UCAR, CERFACS, METEO-FRANCE and IRIT
!----------------------------------------------------------------------
module type_hull

use tools_const, only: zero,two,three,four,pi
use tools_func, only: lonlat2xyz,xyz2lonlat,area,sphere_dist,vector_product
use tools_kinds, only: kind_real,huge_real
use tools_repro, only: infeq,sup,repro_th
use type_mpl, only: mpl_type

implicit none

! Hull derived type
type hull_type
   integer :: nb                            !< Number of hull vertices
   real(kind_real),allocatable :: vbnd(:,:) !< Hull vertices
   real(kind_real) :: area                  !< Hull area

   ! Deprecated: centroid/radius-based hull
   real(kind_real) :: lon                   !< Centroid longitude
   real(kind_real) :: lat                   !< Centroid latitude
   real(kind_real) :: radius                !< Radius
contains
   procedure :: hull_init_empty
   procedure :: hull_init_from_vertices
   procedure :: hull_init_centroid_radius
   generic :: init => hull_init_empty,hull_init_from_vertices,hull_init_centroid_radius
   procedure :: dealloc => hull_dealloc
   procedure :: inside => hull_inside
   procedure :: distance => hull_distance
end type hull_type

private
public :: hull_type

contains

!----------------------------------------------------------------------
! Subroutine: hull_init_empty
!> Allocation and initialization of empty hull
!----------------------------------------------------------------------
subroutine hull_init_empty(hull,mpl)

implicit none

! Passed variables
class(hull_type),intent(inout) :: hull  !< Hull
type(mpl_type),intent(inout) :: mpl     !< MPI data

! Set name
@:set_name(hull_init_empty)

! Missing lon/lat/radius
hull%lon = mpl%msv%valr
hull%lat = mpl%msv%valr
hull%radius = mpl%msv%valr

! No hull vertices
hull%nb = 0

! Allocation
allocate(hull%vbnd(3,hull%nb))

! Whole sphere
hull%area = four*pi

end subroutine hull_init_empty

!----------------------------------------------------------------------
! Subroutine: hull_init_from_vertices
!> Allocation and initialization of hull from vertices
!----------------------------------------------------------------------
subroutine hull_init_from_vertices(hull,n,vbnd)

implicit none

! Passed variables
class(hull_type),intent(inout) :: hull  !< Hull
integer,intent(in) :: n                 !< Size
real(kind_real),intent(in) :: vbnd(3,n) !< Hull vertices

! Local variables
integer :: ib,ibnext
real(kind_real) :: triangle_area
real(kind_real) :: cd(3)

! Set name
@:set_name(hull_init_from_vertices)

! Copy number of hull vertices
hull%nb = n

! Allocation
allocate(hull%vbnd(3,hull%nb))

if (hull%nb>0) then
   ! Copy
   hull%vbnd = vbnd

   ! Centroid
   cd = sum(vbnd,dim=2)
   cd = cd/sqrt(sum(cd**2))

   ! Compute area
   hull%area = zero
   do ib=1,hull%nb
      ! Index
      if (ib<hull%nb) then
         ibnext = ib+1
      else
         ibnext = 1
      end if

      ! Add triangle area
      call area(cd,hull%vbnd(:,ib),hull%vbnd(:,ibnext),triangle_area)
      hull%area = hull%area+triangle_area
   end do
else
   ! Whole sphere
   hull%area = four*pi
end if

end subroutine hull_init_from_vertices

!----------------------------------------------------------------------
! Subroutine: hull_init_centroid_radius
!> Allocation and initialization with centroid and radius
!----------------------------------------------------------------------
subroutine hull_init_centroid_radius(hull,mpl,n,lon,lat,min_radius)

implicit none

! Passed variables
class(hull_type),intent(inout) :: hull   !< Hull
type(mpl_type),intent(inout) :: mpl      !< MPI data
integer,intent(in) :: n                  !< Size
real(kind_real),intent(in) :: lon(n)     !< Longitudes
real(kind_real),intent(in) :: lat(n)     !< Latitudes
real(kind_real),intent(in) :: min_radius !< Minimum radius

! Local variables
integer :: i
real(kind_real) :: dist
real(kind_real) :: cd(3),v(3)

! Set name
@:set_name(hull_init_centroid_radius)

if (n>0) then
   ! Compute centroid
   cd = zero
   do i=1,n
      ! Transform to cartesian coordinates
      call lonlat2xyz(mpl,lon(i),lat(i),v(1),v(2),v(3))

      ! Accumulate
      cd = cd+v
   end do
   if (sum(cd**2)>0) then
      ! Convert centroid back to lon/lat
      call xyz2lonlat(mpl,cd(1),cd(2),cd(3),hull%lon,hull%lat)

      ! Compute hull radius
      hull%radius = 0.0
      do i=1,n
         ! Compute distance to centroid
         call sphere_dist(hull%lon,hull%lat,lon(i),lat(i),dist)

         ! Update hull radius
          if (dist>hull%radius) hull%radius = dist
      end do
   else
      ! Dummy centroid, large radius
      hull%lon = zero
      hull%lat = zero
      hull%radius = two*pi
   end if

   ! Enforce minimum radius
   hull%radius = max(hull%radius,min_radius)
else
   ! Empty universe
   hull%lon = mpl%msv%valr
   hull%lat = mpl%msv%valr
   hull%radius = zero
end if

end subroutine hull_init_centroid_radius

!----------------------------------------------------------------------
! Subroutine: hull_dealloc
!> Release memory
!----------------------------------------------------------------------
subroutine hull_dealloc(hull)

implicit none

! Passed variables
class(hull_type),intent(inout) :: hull !< Hull

! Set name
@:set_name(hull_dealloc)

! Release memory
if (allocated(hull%vbnd)) deallocate(hull%vbnd)

end subroutine hull_dealloc

!----------------------------------------------------------------------
! Subroutine: hull_inside
!> Find whether a point is inside the hull or not
!----------------------------------------------------------------------
subroutine hull_inside(hull,mpl,lon,lat,inside_hull)

implicit none

! Passed variables
class(hull_type),intent(in) :: hull !< Hull
type(mpl_type),intent(inout) :: mpl !< MPI data
real(kind_real),intent(in) :: lon   !< Longitude
real(kind_real),intent(in) :: lat   !< Latitude
logical,intent(out) :: inside_hull  !< True if the point is inside the hull

! Local variables
integer :: ib,ibnext
real(kind_real) :: dist,lontmp,lattmp
real(kind_real) :: vp(3),v1(3),v2(3),cp(3),cd(3)

! Set name
@:set_name(hull_inside)

if (allocated(hull%vbnd)) then
   ! Boundary points-based hull

   ! Transform to cartesian coordinates
   call lonlat2xyz(mpl,lon,lat,vp(1),vp(2),vp(3))

   ! Initialization
   inside_hull = .true.

   do ib=1,hull%nb
      ! Index
      if (ib<hull%nb) then
         ibnext = ib+1
      else
         ibnext = 1
      end if

      ! Check whether points are aligned
      call vector_product(hull%vbnd(:,ib),hull%vbnd(:,ibnext),cp)
      cp = cp/sqrt(sum(cp**2))

      if (sup(abs(sum(vp*cp)),repro_th)) then
         ! Points are not aligned (aligned or almost aligned points are considered inside the hull)

         ! Cross-product
         v1 = hull%vbnd(:,ibnext)-hull%vbnd(:,ib)
         v2 = vp-hull%vbnd(:,ib)
         call vector_product(v1,v2,cp)

         ! Centroid
         cd = vp+hull%vbnd(:,ib)+hull%vbnd(:,ibnext)
         cd = cd/sqrt(sum(cd**2))

         ! Compare the directions
         if (sum(cp*cd)<zero) then
            inside_hull = .false.
            exit
         end if
      end if
   end do
else
   ! Centroid/radius-based hull
   if (mpl%msv%is(hull%radius)) then
      ! Undefined universe
      inside_hull = .true.
   else if (hull%radius>zero) then
      ! Limited universe
      call sphere_dist(hull%lon,hull%lat,lon,lat,dist)
      inside_hull = infeq(dist,hull%radius)
   else
      ! Empty universe
      inside_hull = .false.
   end if
end if

end subroutine hull_inside

!----------------------------------------------------------------------
! Subroutine: hull_distance
!> Find minimum distance to the hull
!----------------------------------------------------------------------
subroutine hull_distance(hull,mpl,lon,lat,dist)

implicit none

! Passed variables
class(hull_type),intent(in) :: hull !< Hull
type(mpl_type),intent(inout) :: mpl !< MPI data
real(kind_real),intent(in) :: lon   !< Longitude
real(kind_real),intent(in) :: lat   !< Latitude
real(kind_real),intent(out) :: dist !< Distance to the hull

! Local variables
integer :: ib,ibnext
real(kind_real) :: dist_test
real(kind_real) :: vp(3),cp(3)

! Set name
@:set_name(hull_distance)

if (allocated(hull%vbnd)) then
   ! Transform to cartesian coordinates
   call lonlat2xyz(mpl,lon,lat,vp(1),vp(2),vp(3))

   ! Initialization
   dist = huge_real

   do ib=1,hull%nb
      ! Index
      if (ib<hull%nb) then
         ibnext = ib+1
      else
         ibnext = 1
      end if

      if ((sum(abs(hull%vbnd(:,ib)-vp))<repro_th).or.(sum(abs(hull%vbnd(:,ibnext)-vp))<repro_th)) then
         ! Point from the hull
         dist = zero
         exit
      else
         ! Distance to the arc
         call vector_product(hull%vbnd(:,ib),hull%vbnd(:,ibnext),cp)
         cp = cp/sqrt(sum(cp**2))
         dist_test = asin(sum(vp*cp))
         if (dist_test<zero) then
            call mpl%abort('${subr}$','point shoud be inside hull to compute distance')
         else
            dist = min(dist,dist_test)
         end if
      end if
   end do
else
   ! Missing value
   dist = mpl%msv%valr
end if

end subroutine hull_distance

end module type_hull

